export module disxx.disasm.Instruction;

export import disxx.disasm.DisassemblyError;
export import disxx.disasm.operand.IOperand;
export import disxx.disasm.InstructionIdentifier;
export import disxx.disasm.Address;
export import disxx.disasm.Bytes;

export import std;

export namespace disxx::disasm
{
	class __attribute__((visibility("default"))) [[nodiscard]] Instruction
	{
	  private:
		// Bunch of operands (may be empty)
		std::vector<std::unique_ptr<operand::IOperand>> m_Operands{};

		// Program-counter relevant address
		std::optional<signed long long int> m_ProgramCounterRelevantAddress{};
		
		// Position of the instruction
		Address m_Address{};
		
		// Raw bytes of the instruction (4 bytes for AArch64)
		Bytes m_Bytes{};

		// ID of the instruction's mnemonic
		InstructionIdentifier m_Identifier{};

	  public:
		explicit Instruction(void) noexcept;

		Instruction(const Instruction &) noexcept;
		Instruction &operator=(const Instruction &) noexcept;

		Instruction(Instruction &&) noexcept;
		Instruction &operator=(Instruction &&) noexcept;

		bool operator==(const Instruction &) noexcept;
		bool operator!=(const Instruction &) noexcept;

		~Instruction(void) noexcept = default;

		inline void SetInstructionIdentifier(InstructionIdentifier &&) noexcept;
		inline void SetOperands(std::vector<std::unique_ptr<operand::IOperand>> &&) noexcept;
		inline void SetProgramCounterRelevantAddress(std::optional<signed long long int> &&) noexcept;
		inline void SetAddress(Address &&) noexcept;
		inline void SetBytes(Bytes &&) noexcept;

		inline const std::vector<std::unique_ptr<operand::IOperand>> &GetOperands(void) const noexcept [[clang::lifetimebound]];
		inline std::optional<signed long long int> GetProgramCounterRelevantAddress(void) const noexcept;
		inline Bytes GetBytes(void) const noexcept;
		inline InstructionIdentifier GetIdentifier(void) const noexcept;
	};

	inline void Instruction::SetInstructionIdentifier(InstructionIdentifier &&insn) noexcept
	{ this->m_Identifier = std::move(insn); }

	inline void Instruction::SetOperands(std::vector<std::unique_ptr<operand::IOperand>> &&oprs) noexcept
	{ this->m_Operands = std::move(oprs); }

	inline void Instruction::SetProgramCounterRelevantAddress(std::optional<signed long long int> &&pc) noexcept
	{ this->m_ProgramCounterRelevantAddress = std::move(pc); }

	inline void Instruction::SetAddress(Address &&addr) noexcept
	{ this->m_Address = std::move(addr); }

	inline void Instruction::SetBytes(Bytes &&bytes) noexcept
	{ this->m_Bytes = std::move(bytes); }
	
	inline const std::vector<std::unique_ptr<operand::IOperand>> &Instruction::GetOperands(void) const noexcept [[clang::lifetimebound]]
	{ return this->m_Operands; }
	
	inline std::optional<signed long long int> Instruction::GetProgramCounterRelevantAddress(void) const noexcept
	{ return this->m_ProgramCounterRelevantAddress; }

	inline Bytes Instruction::GetBytes(void) const noexcept
	{ return this->m_Bytes; }
	
	inline InstructionIdentifier Instruction::GetIdentifier(void) const noexcept
 	{ return this->m_Identifier; }
} /* disxx::disasm */
/*
export template <> struct std::formatter<disxx::disasm::Instruction> : public std::formatter<std::string>
{
  private:
	static const std::unordered_map<InstructionIdentifier, std::string_view> s_MnemonicTable;

  public:
	auto format(const disxx::disasm::Instruction &, std::format_context &) const;
};

const std::unordered_map<InstructionIdentifier, std::string_view> std::formatter<disxx::disasm::Instruction>::s_MnemonicTable = {
	{InstructionIdentifier::ID_UDF, "udf"},
	{InstructionIdentifier::ID_EXT, "ext"},
	{InstructionIdentifier::ID_SXTW, "sxtw"},
	{InstructionIdentifier::ID_UDIV, "udiv"},
	{InstructionIdentifier::ID_SDIV, "sdiv"},
	{InstructionIdentifier::ID_LSLV, "lslv"},
	{InstructionIdentifier::ID_WFIR, "wfir"},
	{InstructionIdentifier::ID_STL1, "stl1"},
	{InstructionIdentifier::ID_LD1R, "ld1r"},
	{InstructionIdentifier::ID_LD3R, "ld3r"},
	{InstructionIdentifier::ID_LD2R, "ld2r"},
	{InstructionIdentifier::ID_LD4R, "ld4r"},
	{InstructionIdentifier::ID_LDAP1, "ldap1"},
	{InstructionIdentifier::ID_LSRV, "lsrv"},
	{InstructionIdentifier::ID_ASRV, "asrv"},
	{InstructionIdentifier::ID_RORV, "rorv"},
	{InstructionIdentifier::ID_GCSPOPM, "gcspopm"},
	{InstructionIdentifier::ID_CRC32B, "crc32b"},
	{InstructionIdentifier::ID_CRC32H, "crc32h"},
	{InstructionIdentifier::ID_CRC32W, "crc32w"},
	{InstructionIdentifier::ID_CRC32CB, "crc32cb"},
	{InstructionIdentifier::ID_CRC32CH, "crc32ch"},
	{InstructionIdentifier::ID_CRC32CW, "crc32cw"},
	{InstructionIdentifier::ID_TCOMMIT, "tcommit"},
	{InstructionIdentifier::ID_SMAX, "smax"},
	{InstructionIdentifier::ID_MRR, "mrr"},
	{InstructionIdentifier::ID_UMAX, "umax"},
	{InstructionIdentifier::ID_SMIN, "smin"},
	{InstructionIdentifier::ID_TBZ, "tbz"},
	{InstructionIdentifier::ID_TBNZ, "tbnz"},
	{InstructionIdentifier::ID_UMIN, "umin"},
	{InstructionIdentifier::ID_SUBP, "subp"},
	{InstructionIdentifier::ID_IRG, "irg"},
	{InstructionIdentifier::ID_GMI, "gmi"},
	{InstructionIdentifier::ID_RPRFM, "rprfm"},
	{InstructionIdentifier::ID_PACGA, "pacga"},
	{InstructionIdentifier::ID_CRC32X, "crc32x"},
	{InstructionIdentifier::ID_CRC32CX, "crc32cx"},
	{InstructionIdentifier::ID_SUBPS, "subps"},
	{InstructionIdentifier::ID_RBIT, "rbit"},
	{InstructionIdentifier::ID_SYSP, "sysp"},
	{InstructionIdentifier::ID_REV16, "rev16"},
	{InstructionIdentifier::ID_REV, "rev"},
	{InstructionIdentifier::ID_CLZ, "clz"},
	{InstructionIdentifier::ID_CLS, "cls"},
	{InstructionIdentifier::ID_CTZ, "ctz"},
	{InstructionIdentifier::ID_CNT, "cnt"},
	{InstructionIdentifier::ID_ABS, "abs"},
	{InstructionIdentifier::ID_REV32, "rev32"},
	{InstructionIdentifier::ID_PACIA, "pacia"},
	{InstructionIdentifier::ID_PACIB, "pacib"},
	{InstructionIdentifier::ID_PACDA, "pacda"},
	{InstructionIdentifier::ID_PACDB, "pacdb"},
	{InstructionIdentifier::ID_AUTIA, "autia"},
	{InstructionIdentifier::ID_AUTIB, "autib"},
	{InstructionIdentifier::ID_AUTDA, "autda"},
	{InstructionIdentifier::ID_AUTDB, "autdb"},
	{InstructionIdentifier::ID_PACIZA, "paciza"},
	{InstructionIdentifier::ID_PACIZB, "pacizb"},
	{InstructionIdentifier::ID_PACDZA, "pacdza"},
	{InstructionIdentifier::ID_PACDZB, "pacdzb"},
	{InstructionIdentifier::ID_AUTIZA, "autiza"},
	{InstructionIdentifier::ID_AUTIZB, "autizb"},
	{InstructionIdentifier::ID_AUTDZA, "autdza"},
	{InstructionIdentifier::ID_AUTDZB, "autdzb"},
	{InstructionIdentifier::ID_XPACI, "xpaci"},
	{InstructionIdentifier::ID_XPACD, "xpacd"},
	{InstructionIdentifier::ID_PACNBIASPPC, "pacnbiasppc"},
	{InstructionIdentifier::ID_PACNBIBSPPC, "pacnbibsppc"},
	{InstructionIdentifier::ID_PACIA171615, "pacia171615"},
	{InstructionIdentifier::ID_PACIB171615, "pacib171615"},
	{InstructionIdentifier::ID_AUTIASPPCR, "autiasppcr"},
	{InstructionIdentifier::ID_AUTIBSPPCR, "autibsppcr"},
	{InstructionIdentifier::ID_PACIASPPC, "paciasppc"},
	{InstructionIdentifier::ID_PACIBSPPC, "pacibsppc"},
	{InstructionIdentifier::ID_AUTIA171615, "autia171615"},
	{InstructionIdentifier::ID_AUTIB171615, "autib171615"},
	{InstructionIdentifier::ID_AND, "and"},
	{InstructionIdentifier::ID_BIC, "bic"},
	{InstructionIdentifier::ID_ORR, "orr"},
	{InstructionIdentifier::ID_MOV, "mov"},
	{InstructionIdentifier::ID_ORN, "orn"},
	{InstructionIdentifier::ID_MVN, "mvn"},
	{InstructionIdentifier::ID_EOR, "eor"},
	{InstructionIdentifier::ID_EON, "eon"},
	{InstructionIdentifier::ID_ANDS, "ands"},
	{InstructionIdentifier::ID_TST, "tst"},
	{InstructionIdentifier::ID_BICS, "bics"},
	{InstructionIdentifier::ID_ADD, "add"},
	{InstructionIdentifier::ID_ADDS, "adds"},
	{InstructionIdentifier::ID_CMN, "cmn"},
	{InstructionIdentifier::ID_SUB, "sub"},
	{InstructionIdentifier::ID_NEG, "neg"},
	{InstructionIdentifier::ID_SUBS, "subs"},
	{InstructionIdentifier::ID_CMP, "cmp"},
	{InstructionIdentifier::ID_ADC, "adc"},
	{InstructionIdentifier::ID_ADCS, "adcs"},
	{InstructionIdentifier::ID_SBC, "sbc"},
	{InstructionIdentifier::ID_NGC, "ngc"},
	{InstructionIdentifier::ID_SBCS, "sbcs"},
	{InstructionIdentifier::ID_NGCS, "ngcs"},
	{InstructionIdentifier::ID_ADDPT, "addpt"},
	{InstructionIdentifier::ID_SUBPT, "subpt"},
	{InstructionIdentifier::ID_SETF8, "setf8"},
	{InstructionIdentifier::ID_SETF16, "setf16"},
	{InstructionIdentifier::ID_CCMN, "ccmn"},
	{InstructionIdentifier::ID_CCMP, "ccmp"},
	{InstructionIdentifier::ID_CSEL, "csel"},
	{InstructionIdentifier::ID_CSINC, "csinc"},
	{InstructionIdentifier::ID_CSINV, "csinv"},
	{InstructionIdentifier::ID_CSNEG, "csneg"},
	{InstructionIdentifier::ID_MADD, "madd"},
	{InstructionIdentifier::ID_MUL, "mul"},
	{InstructionIdentifier::ID_MSUB, "msub"},
	{InstructionIdentifier::ID_MNEG, "mneg"},
	{InstructionIdentifier::ID_SMADDL, "smaddl"},
	{InstructionIdentifier::ID_SMULL, "smull"},
	{InstructionIdentifier::ID_SMSUBL, "smsubl"},
	{InstructionIdentifier::ID_SMNEGL, "smnegl"},
	{InstructionIdentifier::ID_SMULH, "smulh"},
	{InstructionIdentifier::ID_SMADDPT, "smaddpt"},
	{InstructionIdentifier::ID_SMSUBPT, "smsubpt"},
	{InstructionIdentifier::ID_UMADDL, "umaddl"},
	{InstructionIdentifier::ID_UMULL, "umull"},
	{InstructionIdentifier::ID_UMSUBL, "umsubl"},
	{InstructionIdentifier::ID_UMNEGL, "umnegl"},
	{InstructionIdentifier::ID_UMULH, "umulh"},
	{InstructionIdentifier::ID_AUTIASPPC, "autiasppc"},
	{InstructionIdentifier::ID_AUTIBSPPC, "autibsppc"},
	{InstructionIdentifier::ID_ADDG, "addg"},
	{InstructionIdentifier::ID_SUBG, "subg"},
	{InstructionIdentifier::ID_MOVN, "movn"},
	{InstructionIdentifier::ID_MOVZ, "movz"},
	{InstructionIdentifier::ID_MOVK, "movk"},
	{InstructionIdentifier::ID_SXTB, "sxtb"},
	{InstructionIdentifier::ID_SXTH, "sxth"},
	{InstructionIdentifier::ID_UXTB, "uxtb"},
	{InstructionIdentifier::ID_UXTH, "uxth"},
	{InstructionIdentifier::ID_SBFM, "sbfm"},
	{InstructionIdentifier::ID_BFM, "bfm"},
	{InstructionIdentifier::ID_UBFM, "ubfm"},
	{InstructionIdentifier::ID_EXTR, "extr"},
	{InstructionIdentifier::ID_RETAASPPC, "retaasppc"},
	{InstructionIdentifier::ID_RETABSPPC, "retabsppc"},
	{InstructionIdentifier::ID_CBBGT, "cbbgt"},
	{InstructionIdentifier::ID_CBHGT, "cbhgt"},
	{InstructionIdentifier::ID_CBBGE, "cbbge"},
	{InstructionIdentifier::ID_CBHGE, "cbhge"},
	{InstructionIdentifier::ID_CBBHI, "cbbhi"},
	{InstructionIdentifier::ID_CBHHI, "cbhhi"},
	{InstructionIdentifier::ID_CBBHS, "cbbhs"},
	{InstructionIdentifier::ID_CBHHS, "cbhhs"},
	{InstructionIdentifier::ID_CBBEQ, "cbbeq"},
	{InstructionIdentifier::ID_CBHEQ, "cbheq"},
	{InstructionIdentifier::ID_CBBNE, "cbbne"},
	{InstructionIdentifier::ID_CBHNE, "cbhne"},
	{InstructionIdentifier::ID_SVC, "svc"},
	{InstructionIdentifier::ID_HVC, "hvc"},
	{InstructionIdentifier::ID_SMC, "smc"},
	{InstructionIdentifier::ID_BRK, "brk"},
	{InstructionIdentifier::ID_HLT, "hlt"},
	{InstructionIdentifier::ID_TCANCEL, "tcancel"},
	{InstructionIdentifier::ID_DCPS1, "dcps1"},
	{InstructionIdentifier::ID_DCPS2, "dcps2"},
	{InstructionIdentifier::ID_DCPS3, "dcps3"},
	{InstructionIdentifier::ID_NOP, "nop"},
	{InstructionIdentifier::ID_YIELD, "yield"},
	{InstructionIdentifier::ID_WFE, "wfe"},
	{InstructionIdentifier::ID_WFI, "wfi"},
	{InstructionIdentifier::ID_SEV, "sev"},
	{InstructionIdentifier::ID_SEVL, "sevl"},
	{InstructionIdentifier::ID_DGH, "dgh"},
	{InstructionIdentifier::ID_XPACLRI, "xpaclri"},
	{InstructionIdentifier::ID_PACIA1716, "pacia1716"},
	{InstructionIdentifier::ID_PACIB1716, "pacib1716"},
	{InstructionIdentifier::ID_AUTIA1716, "autia1716"},
	{InstructionIdentifier::ID_AUTIB1716, "autib1716"},
	{InstructionIdentifier::ID_ESB, "esb"},
	{InstructionIdentifier::ID_PSB, "psb"},
	{InstructionIdentifier::ID_TSB, "tsb"},
	{InstructionIdentifier::ID_GCSB, "gcsb"},
	{InstructionIdentifier::ID_CSDB, "csdb"},
	{InstructionIdentifier::ID_CLRBHB, "clrbhb"},
	{InstructionIdentifier::ID_PACIAZ, "paciaz"},
	{InstructionIdentifier::ID_PACIASP, "paciasp"},
	{InstructionIdentifier::ID_PACIBZ, "pacibz"},
	{InstructionIdentifier::ID_PACIBSP, "pacibsp"},
	{InstructionIdentifier::ID_AUTIAZ, "autiaz"},
	{InstructionIdentifier::ID_AUTIASP, "autiasp"},
	{InstructionIdentifier::ID_AUTIBZ, "autibz"},
	{InstructionIdentifier::ID_AUTIBSP, "autibsp"},
	{InstructionIdentifier::ID_BTI, "bti"},
	{InstructionIdentifier::ID_PACM, "pacm"},
	{InstructionIdentifier::ID_CHKFEAT, "chkfeat"},
	{InstructionIdentifier::ID_STSHH, "stshh"},
	{InstructionIdentifier::ID_CLREX, "clrex"},
	{InstructionIdentifier::ID_DSB, "dsb"},
	{InstructionIdentifier::ID_DMB, "dmb"},
	{InstructionIdentifier::ID_ISB, "isb"},
	{InstructionIdentifier::ID_SB, "sb"},
	{InstructionIdentifier::ID_OSHLD, "oshld"},
	{InstructionIdentifier::ID_OSHST, "oshst"},
	{InstructionIdentifier::ID_OSH, "osh"},
	{InstructionIdentifier::ID_NSHLD, "nshld"},
	{InstructionIdentifier::ID_NSHST, "nshst"},
	{InstructionIdentifier::ID_NSH, "nsh"},
	{InstructionIdentifier::ID_ISHLD, "ishld"},
	{InstructionIdentifier::ID_ISHST, "ishst"},
	{InstructionIdentifier::ID_ISH, "ish"},
	{InstructionIdentifier::ID_LD, "ld"},
	{InstructionIdentifier::ID_ST, "st"},
	{InstructionIdentifier::ID_SY, "sy"},
	{InstructionIdentifier::ID_CFINV, "cfinv"},
	{InstructionIdentifier::ID_XAFLAG, "xaflag"},
	{InstructionIdentifier::ID_AXFLAG, "axflag"},
	{InstructionIdentifier::ID_TSTART, "tstart"},
	{InstructionIdentifier::ID_TTEST, "ttest"},
	{InstructionIdentifier::ID_GCSSS2, "gcsss2"},
	{InstructionIdentifier::ID_APAS, "apas"},
	{InstructionIdentifier::ID_CFP, "cfp"},
	{InstructionIdentifier::ID_COSP, "cosp"},
	{InstructionIdentifier::ID_CPP, "cpp"},
	{InstructionIdentifier::ID_DVP, "dvp"},
	{InstructionIdentifier::ID_GCSPOPCX, "gcspopcx"},
	{InstructionIdentifier::ID_GCSPOPX, "gcspopx"},
	{InstructionIdentifier::ID_GCSPUSHM, "gcspushm"},
	{InstructionIdentifier::ID_GCSPUSHX, "gcspushx"},
	{InstructionIdentifier::ID_GCSSS1, "gcsss1"},
	{InstructionIdentifier::ID_TRCIT, "trcit"},
	{InstructionIdentifier::ID_S1E1R, "s1e1r"},
	{InstructionIdentifier::ID_S1E1W, "s1e1w"},
	{InstructionIdentifier::ID_S1E0R, "s1e0r"},
	{InstructionIdentifier::ID_S1E0W, "s1e0w"},
	{InstructionIdentifier::ID_S1E1RP, "s1e1rp"},
	{InstructionIdentifier::ID_S1E1WP, "s1e1wp"},
	{InstructionIdentifier::ID_S1E1A, "s1e1a"},
	{InstructionIdentifier::ID_S1E2R, "s1e2r"},
	{InstructionIdentifier::ID_S1E2W, "s1e2w"},
	{InstructionIdentifier::ID_S12E1R, "s12e1r"},
	{InstructionIdentifier::ID_S12E1W, "s12e1w"},
	{InstructionIdentifier::ID_S12E0R, "s12e0r"},
	{InstructionIdentifier::ID_S12E0W, "s12e0w"},
	{InstructionIdentifier::ID_S1E2A, "s1e2a"},
	{InstructionIdentifier::ID_S1E3R, "s1e3r"},
	{InstructionIdentifier::ID_S1E3W, "s1e3w"},
	{InstructionIdentifier::ID_S1E3A, "s1e3a"},
	{InstructionIdentifier::ID_IALL, "iall"},
	{InstructionIdentifier::ID_INJ, "inj"},
	{InstructionIdentifier::ID_IVAC, "ivac"},
	{InstructionIdentifier::ID_ISW, "isw"},
	{InstructionIdentifier::ID_IGVAC, "igvac"},
	{InstructionIdentifier::ID_IGSW, "igsw"},
	{InstructionIdentifier::ID_IGDVAC, "igdvac"},
	{InstructionIdentifier::ID_IGDSW, "igdsw"},
	{InstructionIdentifier::ID_CSW, "csw"},
	{InstructionIdentifier::ID_CGSW, "cgsw"},
	{InstructionIdentifier::ID_CGDSW, "cgdsw"},
	{InstructionIdentifier::ID_CISW, "cisw"},
	{InstructionIdentifier::ID_CIGSW, "cigsw"},
	{InstructionIdentifier::ID_CIGDSW, "cigdsw"},
	{InstructionIdentifier::ID_CIVAPS, "civaps"},
	{InstructionIdentifier::ID_CIGDVAPS, "cigdvaps"},
	{InstructionIdentifier::ID_ZVA, "zva"},
	{InstructionIdentifier::ID_GVA, "gva"},
	{InstructionIdentifier::ID_GZVA, "gzva"},
	{InstructionIdentifier::ID_CVAC, "cvac"},
	{InstructionIdentifier::ID_CGVAC, "cgvac"},
	{InstructionIdentifier::ID_CGDVAC, "cgdvac"},
	{InstructionIdentifier::ID_CVAOC, "cvaoc"},
	{InstructionIdentifier::ID_CVAU, "cvau"},
	{InstructionIdentifier::ID_CGDVAOC, "cgdvaoc"},
	{InstructionIdentifier::ID_CVAP, "cvap"},
	{InstructionIdentifier::ID_CGVAP, "cgvap"},
	{InstructionIdentifier::ID_CGDVAP, "cgdvap"},
	{InstructionIdentifier::ID_CVADP, "cvadp"},
	{InstructionIdentifier::ID_CGVADP, "cgvadp"},
	{InstructionIdentifier::ID_CGDVADP, "cgdvadp"},
	{InstructionIdentifier::ID_CIVAC, "civac"},
	{InstructionIdentifier::ID_CIGVAC, "cigvac"},
	{InstructionIdentifier::ID_CIGDVAC, "cigdvac"},
	{InstructionIdentifier::ID_CIVAOC, "civaoc"},
	{InstructionIdentifier::ID_CIGDVAOC, "cigdvaoc"},
	{InstructionIdentifier::ID_CIPAE, "cipae"},
	{InstructionIdentifier::ID_CIGDPAE, "cigdpae"},
	{InstructionIdentifier::ID_CIPAPA, "cipapa"},
	{InstructionIdentifier::ID_CIGDPAPA, "cigdpapa"},
	{InstructionIdentifier::ID_IALLUIS, "ialluis"},
	{InstructionIdentifier::ID_IALLU, "iallu"},
	{InstructionIdentifier::ID_IVAU, "ivau"},
	{InstructionIdentifier::ID_VMALLE1OS, "vmalle1os"},
	{InstructionIdentifier::ID_VAE1OS, "vae1os"},
	{InstructionIdentifier::ID_ASIDE1OS, "aside1os"},
	{InstructionIdentifier::ID_VAAE1OS, "vaae1os"},
	{InstructionIdentifier::ID_VALE1OS, "vale1os"},
	{InstructionIdentifier::ID_VAALE1OS, "vaale1os"},
	{InstructionIdentifier::ID_RVAE1IS, "rvae1is"},
	{InstructionIdentifier::ID_RVAAE1IS, "rvaae1is"},
	{InstructionIdentifier::ID_RVALE1IS, "rvale1is"},
	{InstructionIdentifier::ID_RVAALE1IS, "rvaale1is"},
	{InstructionIdentifier::ID_VMALLE1IS, "vmalle1is"},
	{InstructionIdentifier::ID_VAE1IS, "vae1is"},
	{InstructionIdentifier::ID_ASIDE1IS, "aside1is"},
	{InstructionIdentifier::ID_VAAE1IS, "vaae1is"},
	{InstructionIdentifier::ID_VALE1IS, "vale1is"},
	{InstructionIdentifier::ID_VAALE1IS, "vaale1is"},
	{InstructionIdentifier::ID_RVAE1OS, "rvae1os"},
	{InstructionIdentifier::ID_RVAAE1OS, "rvaae1os"},
	{InstructionIdentifier::ID_RVALE1OS, "rvale1os"},
	{InstructionIdentifier::ID_RVAALE1OS, "rvaale1os"},
	{InstructionIdentifier::ID_RVAE1, "rvae1"},
	{InstructionIdentifier::ID_RVAAE1, "rvaae1"},
	{InstructionIdentifier::ID_RVALE1, "rvale1"},
	{InstructionIdentifier::ID_RVAALE1, "rvaale1"},
	{InstructionIdentifier::ID_VMALLE1, "vmalle1"},
	{InstructionIdentifier::ID_VAE1, "vae1"},
	{InstructionIdentifier::ID_ASIDE1, "aside1"},
	{InstructionIdentifier::ID_VAAE1, "vaae1"},
	{InstructionIdentifier::ID_VALE1, "vale1"},
	{InstructionIdentifier::ID_VAALE1, "vaale1"},
	{InstructionIdentifier::ID_VMALLE1OSNXS, "vmalle1osnxs"},
	{InstructionIdentifier::ID_VAE1OSNXS, "vae1osnxs"},
	{InstructionIdentifier::ID_ASIDE1OSNXS, "aside1osnxs"},
	{InstructionIdentifier::ID_VAAE1OSNXS, "vaae1osnxs"},
	{InstructionIdentifier::ID_VALE1OSNXS, "vale1osnxs"},
	{InstructionIdentifier::ID_VAALE1OSNXS, "vaale1osnxs"},
	{InstructionIdentifier::ID_RVAE1ISNXS, "rvae1isnxs"},
	{InstructionIdentifier::ID_RVAAE1ISNXS, "rvaae1isnxs"},
	{InstructionIdentifier::ID_RVALE1ISNXS, "rvale1isnxs"},
	{InstructionIdentifier::ID_RVAALE1ISNXS, "rvaale1isnxs"},
	{InstructionIdentifier::ID_VMALLE1ISNXS, "vmalle1isnxs"},
	{InstructionIdentifier::ID_VAE1ISNXS, "vae1isnxs"},
	{InstructionIdentifier::ID_ASIDE1ISNXS, "aside1isnxs"},
	{InstructionIdentifier::ID_VAAE1ISNXS, "vaae1isnxs"},
	{InstructionIdentifier::ID_VALE1ISNXS, "vale1isnxs"},
	{InstructionIdentifier::ID_VAALE1ISNXS, "vaale1isnxs"},
	{InstructionIdentifier::ID_RVAE1OSNXS, "rvae1osnxs"},
	{InstructionIdentifier::ID_RVAAE1OSNXS, "rvaae1osnxs"},
	{InstructionIdentifier::ID_RVALE1OSNXS, "rvale1osnxs"},
	{InstructionIdentifier::ID_RVAALE1OSNXS, "rvaale1osnxs"},
	{InstructionIdentifier::ID_RVAE1NXS, "rvae1nxs"},
	{InstructionIdentifier::ID_RVAAE1NXS, "rvaae1nxs"},
	{InstructionIdentifier::ID_RVALE1NXS, "rvale1nxs"},
	{InstructionIdentifier::ID_RVAALE1NXS, "rvaale1nxs"},
	{InstructionIdentifier::ID_VMALLE1NXS, "vmalle1nxs"},
	{InstructionIdentifier::ID_VAE1NXS, "vae1nxs"},
	{InstructionIdentifier::ID_ASIDE1NXS, "aside1nxs"},
	{InstructionIdentifier::ID_VAAE1NXS, "vaae1nxs"},
	{InstructionIdentifier::ID_VALE1NXS, "vale1nxs"},
	{InstructionIdentifier::ID_VAALE1NXS, "vaale1nxs"},
	{InstructionIdentifier::ID_IPAS2E1IS, "ipas2e1is"},
	{InstructionIdentifier::ID_RIPAS2E1IS, "ripas2e1is"},
	{InstructionIdentifier::ID_IPAS2LE1IS, "ipas2le1is"},
	{InstructionIdentifier::ID_RIPAS2LE1IS, "ripas2le1is"},
	{InstructionIdentifier::ID_ALLE2OS, "alle2os"},
	{InstructionIdentifier::ID_VAE2OS, "vae2os"},
	{InstructionIdentifier::ID_ALLE1OS, "alle1os"},
	{InstructionIdentifier::ID_VALE2OS, "vale2os"},
	{InstructionIdentifier::ID_VMALLS12E1OS, "vmalls12e1os"},
	{InstructionIdentifier::ID_RVAE2IS, "rvae2is"},
	{InstructionIdentifier::ID_VMALLWS2E1IS, "vmallws2e1is"},
	{InstructionIdentifier::ID_RVALE2IS, "rvale2is"},
	{InstructionIdentifier::ID_ALLE2IS, "alle2is"},
	{InstructionIdentifier::ID_VAE2IS, "vae2is"},
	{InstructionIdentifier::ID_ALLE1IS, "alle1is"},
	{InstructionIdentifier::ID_VALE2IS, "vale2is"},
	{InstructionIdentifier::ID_VMALLS12E1IS, "vmalls12e1is"},
	{InstructionIdentifier::ID_IPAS2E1OS, "ipas2e1os"},
	{InstructionIdentifier::ID_IPAS2E1, "ipas2e1"},
	{InstructionIdentifier::ID_RIPAS2E1, "ripas2e1"},
	{InstructionIdentifier::ID_RIPAS2E1OS, "ripas2e1os"},
	{InstructionIdentifier::ID_IPAS2LE1OS, "ipas2le1os"},
	{InstructionIdentifier::ID_IPAS2LE1, "ipas2le1"},
	{InstructionIdentifier::ID_RIPAS2LE1, "ripas2le1"},
	{InstructionIdentifier::ID_RIPAS2LE1OS, "ripas2le1os"},
	{InstructionIdentifier::ID_RVAE2OS, "rvae2os"},
	{InstructionIdentifier::ID_VMALLWS2E1OS, "vmallws2e1os"},
	{InstructionIdentifier::ID_RVALE2OS, "rvale2os"},
	{InstructionIdentifier::ID_RVAE2, "rvae2"},
	{InstructionIdentifier::ID_VMALLWS2E1, "vmallws2e1"},
	{InstructionIdentifier::ID_RVALE2, "rvale2"},
	{InstructionIdentifier::ID_ALLE2, "alle2"},
	{InstructionIdentifier::ID_VAE2, "vae2"},
	{InstructionIdentifier::ID_ALLE1, "alle1"},
	{InstructionIdentifier::ID_VALE2, "vale2"},
	{InstructionIdentifier::ID_VMALLS12E1, "vmalls12e1"},
	{InstructionIdentifier::ID_IPAS2E1ISNXS, "ipas2e1isnxs"},
	{InstructionIdentifier::ID_RIPAS2E1ISNXS, "ripas2e1isnxs"},
	{InstructionIdentifier::ID_IPAS2LE1ISNXS, "ipas2le1isnxs"},
	{InstructionIdentifier::ID_RIPAS2LE1ISNXS, "ripas2le1isnxs"},
	{InstructionIdentifier::ID_ALLE2OSNXS, "alle2osnxs"},
	{InstructionIdentifier::ID_VAE2OSNXS, "vae2osnxs"},
	{InstructionIdentifier::ID_ALLE1OSNXS, "alle1osnxs"},
	{InstructionIdentifier::ID_VALE2OSNXS, "vale2osnxs"},
	{InstructionIdentifier::ID_VMALLS12E1OSNXS, "vmalls12e1osnxs"},
	{InstructionIdentifier::ID_RVAE2ISNXS, "rvae2isnxs"},
	{InstructionIdentifier::ID_VMALLWS2E1ISNXS, "vmallws2e1isnxs"},
	{InstructionIdentifier::ID_RVALE2ISNXS, "rvale2isnxs"},
	{InstructionIdentifier::ID_ALLE2ISNXS, "alle2isnxs"},
	{InstructionIdentifier::ID_VAE2ISNXS, "vae2isnxs"},
	{InstructionIdentifier::ID_ALLE1ISNXS, "alle1isnxs"},
	{InstructionIdentifier::ID_VALE2ISNXS, "vale2isnxs"},
	{InstructionIdentifier::ID_VMALLS12E1ISNXS, "vmalls12e1isnxs"},
	{InstructionIdentifier::ID_IPAS2E1OSNXS, "ipas2e1osnxs"},
	{InstructionIdentifier::ID_IPAS2E1NXS, "ipas2e1nxs"},
	{InstructionIdentifier::ID_RIPAS2E1NXS, "ripas2e1nxs"},
	{InstructionIdentifier::ID_RIPAS2E1OSNXS, "ripas2e1osnxs"},
	{InstructionIdentifier::ID_IPAS2LE1OSNXS, "ipas2le1osnxs"},
	{InstructionIdentifier::ID_IPAS2LE1NXS, "ipas2le1nxs"},
	{InstructionIdentifier::ID_RIPAS2LE1NXS, "ripas2le1nxs"},
	{InstructionIdentifier::ID_RIPAS2LE1OSNXS, "ripas2le1osnxs"},
	{InstructionIdentifier::ID_RVAE2OSNXS, "rvae2osnxs"},
	{InstructionIdentifier::ID_VMALLWS2E1OSNXS, "vmallws2e1osnxs"},
	{InstructionIdentifier::ID_RVALE2OSNXS, "rvale2osnxs"},
	{InstructionIdentifier::ID_RVAE2NXS, "rvae2nxs"},
	{InstructionIdentifier::ID_VMALLWS2E1NXS, "vmallws2e1nxs"},
	{InstructionIdentifier::ID_RVALE2NXS, "rvale2nxs"},
	{InstructionIdentifier::ID_ALLE2NXS, "alle2nxs"},
	{InstructionIdentifier::ID_VAE2NXS, "vae2nxs"},
	{InstructionIdentifier::ID_ALLE1NXS, "alle1nxs"},
	{InstructionIdentifier::ID_VALE2NXS, "vale2nxs"},
	{InstructionIdentifier::ID_VMALLS12E1NXS, "vmalls12e1nxs"},
	{InstructionIdentifier::ID_ALLE3OS, "alle3os"},
	{InstructionIdentifier::ID_VAE3OS, "vae3os"},
	{InstructionIdentifier::ID_PAALLOS, "paallos"},
	{InstructionIdentifier::ID_VALE3OS, "vale3os"},
	{InstructionIdentifier::ID_RVAE3IS, "rvae3is"},
	{InstructionIdentifier::ID_RVALE3IS, "rvale3is"},
	{InstructionIdentifier::ID_ALLE3IS, "alle3is"},
	{InstructionIdentifier::ID_VAE3IS, "vae3is"},
	{InstructionIdentifier::ID_VALE3IS, "vale3is"},
	{InstructionIdentifier::ID_RPAOS, "rpaos"},
	{InstructionIdentifier::ID_RPALOS, "rpalos"},
	{InstructionIdentifier::ID_RVAE3OS, "rvae3os"},
	{InstructionIdentifier::ID_RVALE3OS, "rvale3os"},
	{InstructionIdentifier::ID_RVAE3, "rvae3"},
	{InstructionIdentifier::ID_RVALE3, "rvale3"},
	{InstructionIdentifier::ID_ALLE3, "alle3"},
	{InstructionIdentifier::ID_VAE3, "vae3"},
	{InstructionIdentifier::ID_PAALL, "paall"},
	{InstructionIdentifier::ID_VALE3, "vale3"},
	{InstructionIdentifier::ID_ALLE3OSNXS, "alle3osnxs"},
	{InstructionIdentifier::ID_VAE3OSNXS, "vae3osnxs"},
	{InstructionIdentifier::ID_VALE3OSNXS, "vale3osnxs"},
	{InstructionIdentifier::ID_RVAE3ISNXS, "rvae3isnxs"},
	{InstructionIdentifier::ID_RVALE3ISNXS, "rvale3isnxs"},
	{InstructionIdentifier::ID_ALLE3ISNXS, "alle3isnxs"},
	{InstructionIdentifier::ID_VAE3ISNXS, "vae3isnxs"},
	{InstructionIdentifier::ID_VALE3ISNXS, "vale3isnxs"},
	{InstructionIdentifier::ID_RVAE3OSNXS, "rvae3osnxs"},
	{InstructionIdentifier::ID_RVALE3OSNXS, "rvale3osnxs"},
	{InstructionIdentifier::ID_RVAE3NXS, "rvae3nxs"},
	{InstructionIdentifier::ID_RVALE3NXS, "rvale3nxs"},
	{InstructionIdentifier::ID_ALLE3NXS, "alle3nxs"},
	{InstructionIdentifier::ID_VAE3NXS, "vae3nxs"},
	{InstructionIdentifier::ID_VALE3NXS, "vale3nxs"},
	{InstructionIdentifier::ID_BR, "br"},
	{InstructionIdentifier::ID_BRAAZ, "braaz"},
	{InstructionIdentifier::ID_BRABZ, "brabz"},
	{InstructionIdentifier::ID_BLR, "blr"},
	{InstructionIdentifier::ID_BLRAAZ, "blraaz"},
	{InstructionIdentifier::ID_BLRABZ, "blrabz"},
	{InstructionIdentifier::ID_RET, "ret"},
	{InstructionIdentifier::ID_RETAA, "retaa"},
	{InstructionIdentifier::ID_RETAASPPCR, "retaasppcr"},
	{InstructionIdentifier::ID_RETAB, "retab"},
	{InstructionIdentifier::ID_RETABSPPCR, "retabsppcr"},
	{InstructionIdentifier::ID_ERET, "eret"},
	{InstructionIdentifier::ID_ERETAA, "eretaa"},
	{InstructionIdentifier::ID_ERETAB, "eretab"},
	{InstructionIdentifier::ID_DRPS, "drps"},
	{InstructionIdentifier::ID_BRAA, "braa"},
	{InstructionIdentifier::ID_BRAB, "brab"},
	{InstructionIdentifier::ID_BLRAA, "blraa"},
	{InstructionIdentifier::ID_BLRAB, "blrab"},
	{InstructionIdentifier::ID_CBGT, "cbgt"},
	{InstructionIdentifier::ID_CBGE, "cbge"},
	{InstructionIdentifier::ID_CBHI, "cbhi"},
	{InstructionIdentifier::ID_CBHS, "cbhs"},
	{InstructionIdentifier::ID_CBEQ, "cbeq"},
	{InstructionIdentifier::ID_CBNE, "cbne"},
	{InstructionIdentifier::ID_CBLT, "cblt"},
	{InstructionIdentifier::ID_CBLO, "cblo"},
	{InstructionIdentifier::ID_CASP, "casp"},
	{InstructionIdentifier::ID_CASPL, "caspl"},
	{InstructionIdentifier::ID_CASPA, "caspa"},
	{InstructionIdentifier::ID_CASPAL, "caspal"},
	{InstructionIdentifier::ID_CASPT, "caspt"},
	{InstructionIdentifier::ID_CASPLT, "casplt"},
	{InstructionIdentifier::ID_CASPAT, "caspat"},
	{InstructionIdentifier::ID_CASPALT, "caspalt"},
	{InstructionIdentifier::ID_LDCLRP, "ldclrp"},
	{InstructionIdentifier::ID_LDSETP, "ldsetp"},
	{InstructionIdentifier::ID_SWPP, "swpp"},
	{InstructionIdentifier::ID_RCWCLRP, "rcwclrp"},
	{InstructionIdentifier::ID_RCWSWPP, "rcwswpp"},
	{InstructionIdentifier::ID_RCWSETP, "rcwsetp"},
	{InstructionIdentifier::ID_LDCLRPL, "ldclrpl"},
	{InstructionIdentifier::ID_LDSETPL, "ldsetpl"},
	{InstructionIdentifier::ID_SWPPL, "swppl"},
	{InstructionIdentifier::ID_RCWCLRPL, "rcwclrpl"},
	{InstructionIdentifier::ID_RCWSWPPL, "rcwswppl"},
	{InstructionIdentifier::ID_RCWSETPL, "rcwsetpl"},
	{InstructionIdentifier::ID_LDCLRPA, "ldclrpa"},
	{InstructionIdentifier::ID_LDSETPA, "ldsetpa"},
	{InstructionIdentifier::ID_SWPPA, "swppa"},
	{InstructionIdentifier::ID_RCWCLRPA, "rcwclrpa"},
	{InstructionIdentifier::ID_RCWSWPPA, "rcwswppa"},
	{InstructionIdentifier::ID_RCWSETPA, "rcwsetpa"},
	{InstructionIdentifier::ID_LDCLRPAL, "ldclrpal"},
	{InstructionIdentifier::ID_LDSETPAL, "ldsetpal"},
	{InstructionIdentifier::ID_SWPPAL, "swppal"},
	{InstructionIdentifier::ID_RCWCLRPAL, "rcwclrpal"},
	{InstructionIdentifier::ID_RCWSWPPAL, "rcwswppal"},
	{InstructionIdentifier::ID_RCWSETPAL, "rcwsetpal"},
	{InstructionIdentifier::ID_RCWSCLRP, "rcwsclrp"},
	{InstructionIdentifier::ID_RCWSSWPP, "rcwsswpp"},
	{InstructionIdentifier::ID_RCWSSETP, "rcwssetp"},
	{InstructionIdentifier::ID_RCWSCLRPL, "rcwsclrpl"},
	{InstructionIdentifier::ID_RCWSSWPPL, "rcwsswppl"},
	{InstructionIdentifier::ID_RCWSSETPL, "rcwssetpl"},
	{InstructionIdentifier::ID_RCWSCLRPA, "rcwsclrpa"},
	{InstructionIdentifier::ID_RCWSSWPPA, "rcwsswppa"},
	{InstructionIdentifier::ID_RCWSSETPA, "rcwssetpa"},
	{InstructionIdentifier::ID_RCWSCLRPAL, "rcwsclrpal"},
	{InstructionIdentifier::ID_RCWSSWPPAL, "rcwsswppal"},
	{InstructionIdentifier::ID_RCWSSETPAL, "rcwssetpal"},
	{InstructionIdentifier::ID_LDTADD, "ldtadd"},
	{InstructionIdentifier::ID_STTADD, "sttadd"},
	{InstructionIdentifier::ID_LDTCLR, "ldtclr"},
	{InstructionIdentifier::ID_STTCLR, "sttclr"},
	{InstructionIdentifier::ID_LDTSET, "ldtset"},
	{InstructionIdentifier::ID_STTSET, "sttset"},
	{InstructionIdentifier::ID_SWPT, "swpt"},
	{InstructionIdentifier::ID_LDTADDL, "ldtaddl"},
	{InstructionIdentifier::ID_STTADDL, "sttaddl"},
	{InstructionIdentifier::ID_LDTCLRL, "ldtclrl"},
	{InstructionIdentifier::ID_STTCLRL, "sttclrl"},
	{InstructionIdentifier::ID_LDTSETL, "ldtsetl"},
	{InstructionIdentifier::ID_STTSETL, "sttsetl"},
	{InstructionIdentifier::ID_SWPTL, "swptl"},
	{InstructionIdentifier::ID_LDTADDA, "ldtadda"},
	{InstructionIdentifier::ID_LDTCLRA, "ldtclra"},
	{InstructionIdentifier::ID_LDTSETA, "ldtseta"},
	{InstructionIdentifier::ID_SWPTA, "swpta"},
	{InstructionIdentifier::ID_LDTADDAL, "ldtaddal"},
	{InstructionIdentifier::ID_LDTCLRAL, "ldtclral"},
	{InstructionIdentifier::ID_LDTSETAL, "ldtsetal"},
	{InstructionIdentifier::ID_SWPTAL, "swptal"},
	{InstructionIdentifier::ID_STTXR, "sttxr"},
	{InstructionIdentifier::ID_STLTXR, "stltxr"},
	{InstructionIdentifier::ID_LDTXR, "ldtxr"},
	{InstructionIdentifier::ID_LDATXR, "ldatxr"},
	{InstructionIdentifier::ID_CAST, "cast"},
	{InstructionIdentifier::ID_CASLT, "caslt"},
	{InstructionIdentifier::ID_CASAT, "casat"},
	{InstructionIdentifier::ID_CASALT, "casalt"},
	{InstructionIdentifier::ID_STLURB, "stlurb"},
	{InstructionIdentifier::ID_LDAPURB, "ldapurb"},
	{InstructionIdentifier::ID_LDAPURSB, "ldapursb"},
	{InstructionIdentifier::ID_STLURH, "stlurh"},
	{InstructionIdentifier::ID_LDAPURH, "ldapurh"},
	{InstructionIdentifier::ID_LDAPURSH, "ldapursh"},
	{InstructionIdentifier::ID_STLUR, "stlur"},
	{InstructionIdentifier::ID_LDAPUR, "ldapur"},
	{InstructionIdentifier::ID_LDAPURSW, "ldapursw"},
	{InstructionIdentifier::ID_CPYFP, "cpyfp"},
	{InstructionIdentifier::ID_CPYFM, "cpyfm"},
	{InstructionIdentifier::ID_CPYFE, "cpyfe"},
	{InstructionIdentifier::ID_CPYFPWT, "cpyfpwt"},
	{InstructionIdentifier::ID_CPYFMWT, "cpyfmwt"},
	{InstructionIdentifier::ID_CPYFEWT, "cpyfewt"},
	{InstructionIdentifier::ID_CPYFPRT, "cpyfprt"},
	{InstructionIdentifier::ID_CPYFMRT, "cpyfmrt"},
	{InstructionIdentifier::ID_CPYFERT, "cpyfert"},
	{InstructionIdentifier::ID_CPYFPT, "cpyfpt"},
	{InstructionIdentifier::ID_CPYFMT, "cpyfmt"},
	{InstructionIdentifier::ID_CPYFET, "cpyfet"},
	{InstructionIdentifier::ID_CPYFPWN, "cpyfpwn"},
	{InstructionIdentifier::ID_CPYFMWN, "cpyfmwn"},
	{InstructionIdentifier::ID_CPYFEWN, "cpyfewn"},
	{InstructionIdentifier::ID_CPYFPWTWN, "cpyfpwtwn"},
	{InstructionIdentifier::ID_CPYFMWTWN, "cpyfmwtwn"},
	{InstructionIdentifier::ID_CPYFEWTWN, "cpyfewtwn"},
	{InstructionIdentifier::ID_CPYFPRTWN, "cpyfprtwn"},
	{InstructionIdentifier::ID_CPYFMRTWN, "cpyfmrtwn"},
	{InstructionIdentifier::ID_CPYFERTWN, "cpyfertwn"},
	{InstructionIdentifier::ID_CPYFPTWN, "cpyfptwn"},
	{InstructionIdentifier::ID_CPYFMTWN, "cpyfmtwn"},
	{InstructionIdentifier::ID_CPYFETWN, "cpyfetwn"},
	{InstructionIdentifier::ID_CPYFPRN, "cpyfprn"},
	{InstructionIdentifier::ID_CPYFMRN, "cpyfmrn"},
	{InstructionIdentifier::ID_CPYFERN, "cpyfern"},
	{InstructionIdentifier::ID_CPYFPWTRN, "cpyfpwtrn"},
	{InstructionIdentifier::ID_CPYFMWTRN, "cpyfmwtrn"},
	{InstructionIdentifier::ID_CPYFEWTRN, "cpyfewtrn"},
	{InstructionIdentifier::ID_CPYFPRTRN, "cpyfprtrn"},
	{InstructionIdentifier::ID_CPYFMRTRN, "cpyfmrtrn"},
	{InstructionIdentifier::ID_CPYFERTRN, "cpyfertrn"},
	{InstructionIdentifier::ID_CPYFPTRN, "cpyfptrn"},
	{InstructionIdentifier::ID_CPYFMTRN, "cpyfmtrn"},
	{InstructionIdentifier::ID_CPYFETRN, "cpyfetrn"},
	{InstructionIdentifier::ID_CPYFPN, "cpyfpn"},
	{InstructionIdentifier::ID_CPYFMN, "cpyfmn"},
	{InstructionIdentifier::ID_CPYFEN, "cpyfen"},
	{InstructionIdentifier::ID_CPYFPWTN, "cpyfpwtn"},
	{InstructionIdentifier::ID_CPYFMWTN, "cpyfmwtn"},
	{InstructionIdentifier::ID_CPYFEWTN, "cpyfewtn"},
	{InstructionIdentifier::ID_CPYFPRTN, "cpyfprtn"},
	{InstructionIdentifier::ID_CPYFMRTN, "cpyfmrtn"},
	{InstructionIdentifier::ID_CPYFERTN, "cpyfertn"},
	{InstructionIdentifier::ID_CPYFPTN, "cpyfptn"},
	{InstructionIdentifier::ID_CPYFMTN, "cpyfmtn"},
	{InstructionIdentifier::ID_CPYFETN, "cpyfetn"},
	{InstructionIdentifier::ID_SETP, "setp"},
	{InstructionIdentifier::ID_SETM, "setm"},
	{InstructionIdentifier::ID_SETE, "sete"},
	{InstructionIdentifier::ID_SETPT, "setpt"},
	{InstructionIdentifier::ID_SETMT, "setmt"},
	{InstructionIdentifier::ID_SETET, "setet"},
	{InstructionIdentifier::ID_SETPN, "setpn"},
	{InstructionIdentifier::ID_SETMN, "setmn"},
	{InstructionIdentifier::ID_SETEN, "seten"},
	{InstructionIdentifier::ID_SETPTN, "setptn"},
	{InstructionIdentifier::ID_SETMTN, "setmtn"},
	{InstructionIdentifier::ID_SETETN, "setetn"},
	{InstructionIdentifier::ID_CPYP, "cpyp"},
	{InstructionIdentifier::ID_CPYM, "cpym"},
	{InstructionIdentifier::ID_CPYE, "cpye"},
	{InstructionIdentifier::ID_CPYPWT, "cpypwt"},
	{InstructionIdentifier::ID_CPYMWT, "cpymwt"},
	{InstructionIdentifier::ID_CPYEWT, "cpyewt"},
	{InstructionIdentifier::ID_CPYPRT, "cpyprt"},
	{InstructionIdentifier::ID_CPYMRT, "cpymrt"},
	{InstructionIdentifier::ID_CPYERT, "cpyert"},
	{InstructionIdentifier::ID_CPYPT, "cpypt"},
	{InstructionIdentifier::ID_CPYMT, "cpymt"},
	{InstructionIdentifier::ID_CPYET, "cpyet"},
	{InstructionIdentifier::ID_CPYPWN, "cpypwn"},
	{InstructionIdentifier::ID_CPYMWN, "cpymwn"},
	{InstructionIdentifier::ID_CPYEWN, "cpyewn"},
	{InstructionIdentifier::ID_CPYPWTWN, "cpypwtwn"},
	{InstructionIdentifier::ID_CPYMWTWN, "cpymwtwn"},
	{InstructionIdentifier::ID_CPYEWTWN, "cpyewtwn"},
	{InstructionIdentifier::ID_CPYPRTWN, "cpyprtwn"},
	{InstructionIdentifier::ID_CPYMRTWN, "cpymrtwn"},
	{InstructionIdentifier::ID_CPYERTWN, "cpyertwn"},
	{InstructionIdentifier::ID_CPYPTWN, "cpyptwn"},
	{InstructionIdentifier::ID_CPYMTWN, "cpymtwn"},
	{InstructionIdentifier::ID_CPYETWN, "cpyetwn"},
	{InstructionIdentifier::ID_CPYPRN, "cpyprn"},
	{InstructionIdentifier::ID_CPYMRN, "cpymrn"},
	{InstructionIdentifier::ID_CPYERN, "cpyern"},
	{InstructionIdentifier::ID_CPYPWTRN, "cpypwtrn"},
	{InstructionIdentifier::ID_CPYMWTRN, "cpymwtrn"},
	{InstructionIdentifier::ID_CPYEWTRN, "cpyewtrn"},
	{InstructionIdentifier::ID_CPYPRTRN, "cpyprtrn"},
	{InstructionIdentifier::ID_CPYMRTRN, "cpymrtrn"},
	{InstructionIdentifier::ID_CPYPTRN, "cpyptrn"},
	{InstructionIdentifier::ID_CPYMTRN, "cpymtrn"},
	{InstructionIdentifier::ID_CPYETRN, "cpyetrn"},
	{InstructionIdentifier::ID_CPYPN, "cpypn"},
	{InstructionIdentifier::ID_CPYMN, "cpymn"},
	{InstructionIdentifier::ID_CPYEN, "cpyen"},
	{InstructionIdentifier::ID_CPYPWTN, "cpypwtn"},
	{InstructionIdentifier::ID_CPYMWTN, "cpymwtn"},
	{InstructionIdentifier::ID_CPYEWTN, "cpyewtn"},
	{InstructionIdentifier::ID_CPYPRTN, "cpyprtn"},
	{InstructionIdentifier::ID_CPYMRTN, "cpymrtn"},
	{InstructionIdentifier::ID_CPYERTN, "cpyertn"},
	{InstructionIdentifier::ID_CPYPTN, "cpyptn"},
	{InstructionIdentifier::ID_CPYMTN, "cpymtn"},
	{InstructionIdentifier::ID_CPYETN, "cpyetn"},
	{InstructionIdentifier::ID_SETGP, "setgp"},
	{InstructionIdentifier::ID_SETGM, "setgm"},
	{InstructionIdentifier::ID_SETGE, "setge"},
	{InstructionIdentifier::ID_SETGPT, "setgpt"},
	{InstructionIdentifier::ID_SETGMT, "setgmt"},
	{InstructionIdentifier::ID_SETGET, "setget"},
	{InstructionIdentifier::ID_SETGPN, "setgpn"},
	{InstructionIdentifier::ID_SETGMN, "setgmn"},
	{InstructionIdentifier::ID_SETGEN, "setgen"},
	{InstructionIdentifier::ID_SETGPTN, "setgptn"},
	{InstructionIdentifier::ID_SETGMTN, "setgmtn"},
	{InstructionIdentifier::ID_SETGETN, "setgetn"},
	{InstructionIdentifier::ID_STNP, "stnp"},
	{InstructionIdentifier::ID_LDNP, "ldnp"},
	{InstructionIdentifier::ID_STTNP, "sttnp"},
	{InstructionIdentifier::ID_LDTNP, "ldtnp"},
	{InstructionIdentifier::ID_STP, "stp"},
	{InstructionIdentifier::ID_LDP, "ldp"},
	{InstructionIdentifier::ID_STGP, "stgp"},
	{InstructionIdentifier::ID_LDPSW, "ldpsw"},
	{InstructionIdentifier::ID_STTP, "sttp"},
	{InstructionIdentifier::ID_LDTP, "ldtp"},
	{InstructionIdentifier::ID_STURB, "sturb"},
	{InstructionIdentifier::ID_LDURB, "ldurb"},
	{InstructionIdentifier::ID_LDURSB, "ldursb"},
	{InstructionIdentifier::ID_STUR, "stur"},
	{InstructionIdentifier::ID_LDUR, "ldur"},
	{InstructionIdentifier::ID_STURH, "sturh"},
	{InstructionIdentifier::ID_LDURH, "ldurh"},
	{InstructionIdentifier::ID_LDURSH, "ldursh"},
	{InstructionIdentifier::ID_LDURSW, "ldursw"},
	{InstructionIdentifier::ID_STRB, "strb"},
	{InstructionIdentifier::ID_LDRB, "ldrb"},
	{InstructionIdentifier::ID_LDRSB, "ldrsb"},
	{InstructionIdentifier::ID_STR, "str"},
	{InstructionIdentifier::ID_LDR, "ldr"},
	{InstructionIdentifier::ID_STRH, "strh"},
	{InstructionIdentifier::ID_LDRH, "ldrh"},
	{InstructionIdentifier::ID_LDRSH, "ldrsh"},
	{InstructionIdentifier::ID_LDRSW, "ldrsw"},
	{InstructionIdentifier::ID_STTRB, "sttrb"},
	{InstructionIdentifier::ID_LDTRB, "ldtrb"},
	{InstructionIdentifier::ID_LDTRSB, "ldtrsb"},
	{InstructionIdentifier::ID_STTRH, "sttrh"},
	{InstructionIdentifier::ID_LDTRH, "ldtrh"},
	{InstructionIdentifier::ID_LDTRSH, "ldtrsh"},
	{InstructionIdentifier::ID_STTR, "sttr"},
	{InstructionIdentifier::ID_LDTR, "ldtr"},
	{InstructionIdentifier::ID_LDTRSW, "ldtrsw"},
	{InstructionIdentifier::ID_LDADDB, "ldaddb"},
	{InstructionIdentifier::ID_STADDB, "staddb"},
	{InstructionIdentifier::ID_LDADDLB, "ldaddlb"},
	{InstructionIdentifier::ID_STADDLB, "staddlb"},
	{InstructionIdentifier::ID_LDADDAB, "ldaddab"},
	{InstructionIdentifier::ID_LDADDALB, "ldaddalb"},
	{InstructionIdentifier::ID_LDCLRB, "ldclrb"},
	{InstructionIdentifier::ID_STCLRB, "stclrb"},
	{InstructionIdentifier::ID_LDCLRLB, "ldclrlb"},
	{InstructionIdentifier::ID_STCLRLB, "stclrlb"},
	{InstructionIdentifier::ID_LDCLRAB, "ldclrab"},
	{InstructionIdentifier::ID_LDCLRALB, "ldclralb"},
	{InstructionIdentifier::ID_LDEORB, "ldeorb"},
	{InstructionIdentifier::ID_STEORB, "steorb"},
	{InstructionIdentifier::ID_LDEORLB, "ldeorlb"},
	{InstructionIdentifier::ID_STEORLB, "steorlb"},
	{InstructionIdentifier::ID_LDEORAB, "ldeorab"},
	{InstructionIdentifier::ID_LDEORALB, "ldeoralb"},
	{InstructionIdentifier::ID_LDSETB, "ldsetb"},
	{InstructionIdentifier::ID_STSETB, "stsetb"},
	{InstructionIdentifier::ID_LDSETLB, "ldsetlb"},
	{InstructionIdentifier::ID_STSETLB, "stsetlb"},
	{InstructionIdentifier::ID_LDSETAB, "ldsetab"},
	{InstructionIdentifier::ID_LDSETALB, "ldsetalb"},
	{InstructionIdentifier::ID_LDSMAXB, "ldsmaxb"},
	{InstructionIdentifier::ID_STSMAXB, "stsmaxb"},
	{InstructionIdentifier::ID_LDSMAXLB, "ldsmaxlb"},
	{InstructionIdentifier::ID_STSMAXLB, "stsmaxlb"},
	{InstructionIdentifier::ID_LDSMAXAB, "ldsmaxab"},
	{InstructionIdentifier::ID_LDSMAXALB, "ldsmaxalb"},
	{InstructionIdentifier::ID_LDSMINB, "ldsminb"},
	{InstructionIdentifier::ID_STSMINB, "stsminb"},
	{InstructionIdentifier::ID_LDSMINLB, "ldsminlb"},
	{InstructionIdentifier::ID_STSMINLB, "stsminlb"},
	{InstructionIdentifier::ID_LDSMINAB, "ldsminab"},
	{InstructionIdentifier::ID_LDSMINALB, "ldsminalb"},
	{InstructionIdentifier::ID_LDUMAXB, "ldumaxb"},
	{InstructionIdentifier::ID_STUMAXB, "stumaxb"},
	{InstructionIdentifier::ID_LDUMAXLB, "ldumaxlb"},
	{InstructionIdentifier::ID_STUMAXLB, "stumaxlb"},
	{InstructionIdentifier::ID_LDUMAXAB, "ldumaxab"},
	{InstructionIdentifier::ID_LDUMAXALB, "ldumaxalb"},
	{InstructionIdentifier::ID_LDUMINB, "lduminb"},
	{InstructionIdentifier::ID_STUMINB, "stuminb"},
	{InstructionIdentifier::ID_LDUMINLB, "lduminlb"},
	{InstructionIdentifier::ID_STUMINLB, "stuminlb"},
	{InstructionIdentifier::ID_LDUMINAB, "lduminab"},
	{InstructionIdentifier::ID_LDUMINALB, "lduminalb"},
	{InstructionIdentifier::ID_SWPB, "swpb"},
	{InstructionIdentifier::ID_SWPLB, "swplb"},
	{InstructionIdentifier::ID_SWPAB, "swpab"},
	{InstructionIdentifier::ID_SWPALB, "swpalb"},
	{InstructionIdentifier::ID_LDAPRB, "ldaprb"},
	{InstructionIdentifier::ID_LDADDH, "ldaddh"},
	{InstructionIdentifier::ID_STADDH, "staddh"},
	{InstructionIdentifier::ID_LDADDLH, "ldaddlh"},
	{InstructionIdentifier::ID_STADDLH, "staddlh"},
	{InstructionIdentifier::ID_LDADDAH, "ldaddah"},
	{InstructionIdentifier::ID_LDADDALH, "ldaddalh"},
	{InstructionIdentifier::ID_LDCLRH, "ldclrh"},
	{InstructionIdentifier::ID_STCLRH, "stclrh"},
	{InstructionIdentifier::ID_LDCLRLH, "ldclrlh"},
	{InstructionIdentifier::ID_STCLRLH, "stclrlh"},
	{InstructionIdentifier::ID_LDCLRAH, "ldclrah"},
	{InstructionIdentifier::ID_LDCLRALH, "ldclralh"},
	{InstructionIdentifier::ID_LDEORH, "ldeorh"},
	{InstructionIdentifier::ID_STEORH, "steorh"},
	{InstructionIdentifier::ID_LDEORLH, "ldeorlh"},
	{InstructionIdentifier::ID_STEORLH, "steorlh"},
	{InstructionIdentifier::ID_LDEORAH, "ldeorah"},
	{InstructionIdentifier::ID_LDEORALH, "ldeoralh"},
	{InstructionIdentifier::ID_LDSETH, "ldseth"},
	{InstructionIdentifier::ID_STSETH, "stseth"},
	{InstructionIdentifier::ID_LDSETLH, "ldsetlh"},
	{InstructionIdentifier::ID_STSETLH, "stsetlh"},
	{InstructionIdentifier::ID_LDSETAH, "ldsetah"},
	{InstructionIdentifier::ID_LDSETALH, "ldsetalh"},
	{InstructionIdentifier::ID_LDSMAXH, "ldsmaxh"},
	{InstructionIdentifier::ID_STSMAXH, "stsmaxh"},
	{InstructionIdentifier::ID_LDSMAXLH, "ldsmaxlh"},
	{InstructionIdentifier::ID_STSMAXLH, "stsmaxlh"},
	{InstructionIdentifier::ID_LDSMAXAH, "ldsmaxah"},
	{InstructionIdentifier::ID_LDSMAXALH, "ldsmaxalh"},
	{InstructionIdentifier::ID_LDSMINH, "ldsminh"},
	{InstructionIdentifier::ID_STSMINH, "stsminh"},
	{InstructionIdentifier::ID_LDSMINLH, "ldsminlh"},
	{InstructionIdentifier::ID_STSMINLH, "stsminlh"},
	{InstructionIdentifier::ID_LDSMINAH, "ldsminah"},
	{InstructionIdentifier::ID_LDSMINALH, "ldsminalh"},
	{InstructionIdentifier::ID_LDUMAXH, "ldumaxh"},
	{InstructionIdentifier::ID_STUMAXH, "stumaxh"},
	{InstructionIdentifier::ID_LDUMAXLH, "ldumaxlh"},
	{InstructionIdentifier::ID_STUMAXLH, "stumaxlh"},
	{InstructionIdentifier::ID_LDUMAXAH, "ldumaxah"},
	{InstructionIdentifier::ID_LDUMAXALH, "ldumaxalh"},
	{InstructionIdentifier::ID_LDUMINH, "lduminh"},
	{InstructionIdentifier::ID_STUMINH, "stuminh"},
	{InstructionIdentifier::ID_LDUMINLH, "lduminlh"},
	{InstructionIdentifier::ID_STUMINLH, "stuminlh"},
	{InstructionIdentifier::ID_LDUMINAH, "lduminah"},
	{InstructionIdentifier::ID_LDUMINALH, "lduminalh"},
	{InstructionIdentifier::ID_SWPH, "swph"},
	{InstructionIdentifier::ID_SWPLH, "swplh"},
	{InstructionIdentifier::ID_SWPAH, "swpah"},
	{InstructionIdentifier::ID_SWPALH, "swpalh"},
	{InstructionIdentifier::ID_LDAPRH, "ldaprh"},
	{InstructionIdentifier::ID_LDADD, "ldadd"},
	{InstructionIdentifier::ID_STADD, "stadd"},
	{InstructionIdentifier::ID_LDADDL, "ldaddl"},
	{InstructionIdentifier::ID_STADDL, "staddl"},
	{InstructionIdentifier::ID_LDADDA, "ldadda"},
	{InstructionIdentifier::ID_LDADDAL, "ldaddal"},
	{InstructionIdentifier::ID_LDCLR, "ldclr"},
	{InstructionIdentifier::ID_STCLR, "stclr"},
	{InstructionIdentifier::ID_LDCLRL, "ldclrl"},
	{InstructionIdentifier::ID_STCLRL, "stclrl"},
	{InstructionIdentifier::ID_LDCLRA, "ldclra"},
	{InstructionIdentifier::ID_LDCLRAL, "ldclral"},
	{InstructionIdentifier::ID_LDEOR, "ldeor"},
	{InstructionIdentifier::ID_STEOR, "steor"},
	{InstructionIdentifier::ID_LDEORL, "ldeorl"},
	{InstructionIdentifier::ID_STEORL, "steorl"},
	{InstructionIdentifier::ID_LDEORA, "ldeora"},
	{InstructionIdentifier::ID_LDEORAL, "ldeoral"},
	{InstructionIdentifier::ID_LDSET, "ldset"},
	{InstructionIdentifier::ID_STSET, "stset"},
	{InstructionIdentifier::ID_LDSETL, "ldsetl"},
	{InstructionIdentifier::ID_STSETL, "stsetl"},
	{InstructionIdentifier::ID_LDSETA, "ldseta"},
	{InstructionIdentifier::ID_LDSETAL, "ldsetal"},
	{InstructionIdentifier::ID_LDSMAX, "ldsmax"},
	{InstructionIdentifier::ID_STSMAX, "stsmax"},
	{InstructionIdentifier::ID_LDSMAXL, "ldsmaxl"},
	{InstructionIdentifier::ID_STSMAXL, "stsmaxl"},
	{InstructionIdentifier::ID_LDSMAXA, "ldsmaxa"},
	{InstructionIdentifier::ID_LDSMAXAL, "ldsmaxal"},
	{InstructionIdentifier::ID_LDSMIN, "ldsmin"},
	{InstructionIdentifier::ID_STSMIN, "stsmin"},
	{InstructionIdentifier::ID_LDSMINL, "ldsminl"},
	{InstructionIdentifier::ID_STSMINL, "stsminl"},
	{InstructionIdentifier::ID_LDSMINA, "ldsmina"},
	{InstructionIdentifier::ID_LDSMINAL, "ldsminal"},
	{InstructionIdentifier::ID_LDUMAX, "ldumax"},
	{InstructionIdentifier::ID_STUMAX, "stumax"},
	{InstructionIdentifier::ID_LDUMAXL, "ldumaxl"},
	{InstructionIdentifier::ID_STUMAXL, "stumaxl"},
	{InstructionIdentifier::ID_LDUMAXA, "ldumaxa"},
	{InstructionIdentifier::ID_LDUMAXAL, "ldumaxal"},
	{InstructionIdentifier::ID_LDUMIN, "ldumin"},
	{InstructionIdentifier::ID_STUMIN, "stumin"},
	{InstructionIdentifier::ID_LDUMINL, "lduminl"},
	{InstructionIdentifier::ID_STUMINL, "stuminl"},
	{InstructionIdentifier::ID_LDUMINA, "ldumina"},
	{InstructionIdentifier::ID_LDUMINAL, "lduminal"},
	{InstructionIdentifier::ID_SWP, "swp"},
	{InstructionIdentifier::ID_SWPL, "swpl"},
	{InstructionIdentifier::ID_SWPA, "swpa"},
	{InstructionIdentifier::ID_SWPAL, "swpal"},
	{InstructionIdentifier::ID_LDAPR, "ldapr"},
	{InstructionIdentifier::ID_ST64BVO, "st64bvo"},
	{InstructionIdentifier::ID_ST64BV, "st64bv"},
	{InstructionIdentifier::ID_LDBFADD, "ldbfadd"},
	{InstructionIdentifier::ID_LDBFADDL, "ldbfaddl"},
	{InstructionIdentifier::ID_LDBFADDA, "ldbfadda"},
	{InstructionIdentifier::ID_LDBFADDAL, "ldbfaddal"},
	{InstructionIdentifier::ID_LDBFMAX, "ldbfmax"},
	{InstructionIdentifier::ID_LDBFMAXL, "ldbfmaxl"},
	{InstructionIdentifier::ID_LDBFMAXA, "ldbfmaxa"},
	{InstructionIdentifier::ID_LDBFMAXAL, "ldbfmaxal"},
	{InstructionIdentifier::ID_LDBFMIN, "ldbfmin"},
	{InstructionIdentifier::ID_LDBFMINL, "ldbfminl"},
	{InstructionIdentifier::ID_LDBFMINA, "ldbfmina"},
	{InstructionIdentifier::ID_LDBFMINAL, "ldbfminal"},
	{InstructionIdentifier::ID_LDBFMAXNM, "ldbfmaxnm"},
	{InstructionIdentifier::ID_LDBFMAXNML, "ldbfmaxnml"},
	{InstructionIdentifier::ID_LDBFMAXNMA, "ldbfmaxnma"},
	{InstructionIdentifier::ID_LDBFMAXNMAL, "ldbfmaxnmal"},
	{InstructionIdentifier::ID_LDBFMINNM, "ldbfminnm"},
	{InstructionIdentifier::ID_LDBFMINNML, "ldbfminnml"},
	{InstructionIdentifier::ID_LDBFMINNMA, "ldbfminnma"},
	{InstructionIdentifier::ID_LDBFMINNMAL, "ldbfminnmal"},
	{InstructionIdentifier::ID_LDFADD, "ldfadd"},
	{InstructionIdentifier::ID_LDFADDL, "ldfaddl"},
	{InstructionIdentifier::ID_LDFADDA, "ldfadda"},
	{InstructionIdentifier::ID_LDFADDAL, "ldfaddal"},
	{InstructionIdentifier::ID_LDFMAX, "ldfmax"},
	{InstructionIdentifier::ID_LDFMAXL, "ldfmaxl"},
	{InstructionIdentifier::ID_LDFMAXA, "ldfmaxa"},
	{InstructionIdentifier::ID_LDFMAXAL, "ldfmaxal"},
	{InstructionIdentifier::ID_LDFMIN, "ldfmin"},
	{InstructionIdentifier::ID_LDFMINL, "ldfminl"},
	{InstructionIdentifier::ID_LDFMINA, "ldfmina"},
	{InstructionIdentifier::ID_LDFMINAL, "ldfminal"},
	{InstructionIdentifier::ID_LDFMAXNM, "ldfmaxnm"},
	{InstructionIdentifier::ID_LDFMAXNML, "ldfmaxnml"},
	{InstructionIdentifier::ID_LDFMAXNMA, "ldfmaxnma"},
	{InstructionIdentifier::ID_LDFMAXNMAL, "ldfmaxnmal"},
	{InstructionIdentifier::ID_LDFMINNM, "ldfminnm"},
	{InstructionIdentifier::ID_LDFMINNML, "ldfminnml"},
	{InstructionIdentifier::ID_LDFMINNMA, "ldfminnma"},
	{InstructionIdentifier::ID_LDFMINNMAL, "ldfminnmal"},
	{InstructionIdentifier::ID_STBFADD, "stbfadd"},
	{InstructionIdentifier::ID_STBFADDL, "stbfaddl"},
	{InstructionIdentifier::ID_STBFMAX, "stbfmax"},
	{InstructionIdentifier::ID_STBFMAXL, "stbfmaxl"},
	{InstructionIdentifier::ID_STBFMIN, "stbfmin"},
	{InstructionIdentifier::ID_STBFMINL, "stbfminl"},
	{InstructionIdentifier::ID_STBFMAXNM, "stbfmaxnm"},
	{InstructionIdentifier::ID_STBFMAXNML, "stbfmaxnml"},
	{InstructionIdentifier::ID_STBFMINNM, "stbfminnm"},
	{InstructionIdentifier::ID_STBFMINNML, "stbfminnml"},
	{InstructionIdentifier::ID_STFADD, "stfadd"},
	{InstructionIdentifier::ID_STFADDL, "stfaddl"},
	{InstructionIdentifier::ID_STFMAX, "stfmax"},
	{InstructionIdentifier::ID_STFMAXL, "stfmaxl"},
	{InstructionIdentifier::ID_STFMIN, "stfmin"},
	{InstructionIdentifier::ID_STFMINL, "stfminl"},
	{InstructionIdentifier::ID_STFMAXNM, "stfmaxnm"},
	{InstructionIdentifier::ID_STFMAXNML, "stfmaxnml"},
	{InstructionIdentifier::ID_STFMINNM, "stfminnm"},
	{InstructionIdentifier::ID_STFMINNML, "stfminnml"},
	{InstructionIdentifier::ID_RCWCLR, "rcwclr"},
	{InstructionIdentifier::ID_RCWCLRL, "rcwclrl"},
	{InstructionIdentifier::ID_RCWCLRA, "rcwclra"},
	{InstructionIdentifier::ID_RCWCLRAL, "rcwclral"},
	{InstructionIdentifier::ID_RCWSWP, "rcwswp"},
	{InstructionIdentifier::ID_RCWSWPL, "rcwswpl"},
	{InstructionIdentifier::ID_RCWSWPA, "rcwswpa"},
	{InstructionIdentifier::ID_RCWSWPAL, "rcwswpal"},
	{InstructionIdentifier::ID_RCWSET, "rcwset"},
	{InstructionIdentifier::ID_RCWSETL, "rcwsetl"},
	{InstructionIdentifier::ID_RCWSETA, "rcwseta"},
	{InstructionIdentifier::ID_RCWSETAL, "rcwsetal"},
	{InstructionIdentifier::ID_RCWSCLR, "rcwsclr"},
	{InstructionIdentifier::ID_RCWSCLRL, "rcwsclrl"},
	{InstructionIdentifier::ID_RCWSCLRA, "rcwsclra"},
	{InstructionIdentifier::ID_RCWSCLRAL, "rcwsclral"},
	{InstructionIdentifier::ID_RCWSSWP, "rcwsswp"},
	{InstructionIdentifier::ID_RCWSSWPL, "rcwsswpl"},
	{InstructionIdentifier::ID_RCWSSWPA, "rcwsswpa"},
	{InstructionIdentifier::ID_RCWSSWPAL, "rcwsswpal"},
	{InstructionIdentifier::ID_RCWSSET, "rcwsset"},
	{InstructionIdentifier::ID_RCWSSETL, "rcwssetl"},
	{InstructionIdentifier::ID_RCWSSETA, "rcwsseta"},
	{InstructionIdentifier::ID_RCWSSETAL, "rcwssetal"},
	{InstructionIdentifier::ID_ST64B, "st64b"},
	{InstructionIdentifier::ID_LD64B, "ld64b"},
	{InstructionIdentifier::ID_PLDKEEP, "pldkeep"},
	{InstructionIdentifier::ID_PSTKEEP, "pstkeep"},
	{InstructionIdentifier::ID_PLDSTRM, "pldstrm"},
	{InstructionIdentifier::ID_PSTSTRM, "pststrm"},
	{InstructionIdentifier::ID_AESE, "aese"},
	{InstructionIdentifier::ID_AESD, "aesd"},
	{InstructionIdentifier::ID_AESMC, "aesmc"},
	{InstructionIdentifier::ID_AESIMC, "aesimc"},
	{InstructionIdentifier::ID_SHA1C, "sha1c"},
	{InstructionIdentifier::ID_SHA1P, "sha1p"},
	{InstructionIdentifier::ID_SHA1M, "sha1m"},
	{InstructionIdentifier::ID_SHA1SUO, "sha1suo"},
	{InstructionIdentifier::ID_SHA256H, "sha256h"},
	{InstructionIdentifier::ID_SHA256H2, "sha256h2"},
	{InstructionIdentifier::ID_SHA256SU1, "sha256su1"},
	{InstructionIdentifier::ID_SHA1H, "sha1h"},
	{InstructionIdentifier::ID_SHA1SU1, "sha1su1"},
	{InstructionIdentifier::ID_SHA256SU0, "sha256su0"},
	{InstructionIdentifier::ID_FMULX, "fmulx"},
	{InstructionIdentifier::ID_FCMEQ, "fcmeq"},
	{InstructionIdentifier::ID_FRECPS, "frecps"},
	{InstructionIdentifier::ID_FRSQRTS, "frsqrts"},
	{InstructionIdentifier::ID_FCMGE, "fcmge"},
	{InstructionIdentifier::ID_FACGE, "facge"},
	{InstructionIdentifier::ID_FABD, "fabd"},
	{InstructionIdentifier::ID_FCMGT, "fcmgt"},
	{InstructionIdentifier::ID_FACGT, "facgt"},
	{InstructionIdentifier::ID_FCVTNS, "fcvtns"},
	{InstructionIdentifier::ID_FCVTMS, "fcvtms"},
	{InstructionIdentifier::ID_FCVTAS, "fcvtas"},
	{InstructionIdentifier::ID_SCVTF, "scvtf"},
	{InstructionIdentifier::ID_FCMLT, "fcmlt"},
	{InstructionIdentifier::ID_FCVTPS, "fcvtps"},
	{InstructionIdentifier::ID_FCVTZS, "fcvtzs"},
	{InstructionIdentifier::ID_FRECPE, "frecpe"},
	{InstructionIdentifier::ID_FRECPX, "frecpx"},
	{InstructionIdentifier::ID_FCVTNU, "fcvtnu"},
	{InstructionIdentifier::ID_FCVTMU, "fcvtmu"},
	{InstructionIdentifier::ID_FCVTAU, "fcvtau"},
	{InstructionIdentifier::ID_UCVTF, "ucvtf"},
	{InstructionIdentifier::ID_FCMLE, "fcmle"},
	{InstructionIdentifier::ID_FCVTPU, "fcvtpu"},
	{InstructionIdentifier::ID_FCVTZU, "fcvtzu"},
	{InstructionIdentifier::ID_FRSQRTE, "frsqrte"},
	{InstructionIdentifier::ID_SUQADD, "suqadd"},
	{InstructionIdentifier::ID_SQABS, "sqabs"},
	{InstructionIdentifier::ID_SQXTN, "sqxtn"},
	{InstructionIdentifier::ID_USQADD, "usqadd"},
	{InstructionIdentifier::ID_SQNEG, "sqneg"},
	{InstructionIdentifier::ID_SQXTUN, "sqxtun"},
	{InstructionIdentifier::ID_UQXTN, "uqxtn"},
	{InstructionIdentifier::ID_CMGT, "cmgt"},
	{InstructionIdentifier::ID_CMEQ, "cmeq"},
	{InstructionIdentifier::ID_CMLT, "cmlt"},
	{InstructionIdentifier::ID_FCVTXN, "fcvtxn"},
	{InstructionIdentifier::ID_CMGE, "cmge"},
	{InstructionIdentifier::ID_CMLE, "cmle"},
	{InstructionIdentifier::ID_FMAXNMP, "fmaxnmp"},
	{InstructionIdentifier::ID_FADDP, "faddp"},
	{InstructionIdentifier::ID_FMAXP, "fmaxp"},
	{InstructionIdentifier::ID_FMINNMP, "fminnmp"},
	{InstructionIdentifier::ID_FMINP, "fminp"},
	{InstructionIdentifier::ID_ADDP, "addp"},
	{InstructionIdentifier::ID_SQDMLAL, "sqdmlal"},
	{InstructionIdentifier::ID_SQDMLSL, "sqdmlsl"},
	{InstructionIdentifier::ID_SQDMULL, "sqdmull"},
	{InstructionIdentifier::ID_SQADD, "sqadd"},
	{InstructionIdentifier::ID_SQSUB, "sqsub"},
	{InstructionIdentifier::ID_SQSHL, "sqshl"},
	{InstructionIdentifier::ID_SQRSHL, "sqrshl"},
	{InstructionIdentifier::ID_SQDMULH, "sqdmulh"},
	{InstructionIdentifier::ID_UQADD, "uqadd"},
	{InstructionIdentifier::ID_UQSUB, "uqsub"},
	{InstructionIdentifier::ID_UQSHL, "uqshl"},
	{InstructionIdentifier::ID_UQRSHL, "uqrshl"},
	{InstructionIdentifier::ID_SQRDMULH, "sqrdmulh"},
	{InstructionIdentifier::ID_SSHL, "sshl"},
	{InstructionIdentifier::ID_SRSHL, "srshl"},
	{InstructionIdentifier::ID_CMTST, "cmtst"},
	{InstructionIdentifier::ID_CMHI, "cmhi"},
	{InstructionIdentifier::ID_CMHS, "cmhs"},
	{InstructionIdentifier::ID_USHL, "ushl"},
	{InstructionIdentifier::ID_URSHL, "urshl"},
	{InstructionIdentifier::ID_SSHR, "sshr"},
	{InstructionIdentifier::ID_SSRA, "ssra"},
	{InstructionIdentifier::ID_SRSHR, "srshr"},
	{InstructionIdentifier::ID_SRSRA, "srsra"},
	{InstructionIdentifier::ID_SHL, "shl"},
	{InstructionIdentifier::ID_SQSHRN, "sqshrn"},
	{InstructionIdentifier::ID_SQRSHRN, "sqrshrn"},
	{InstructionIdentifier::ID_USHR, "ushr"},
	{InstructionIdentifier::ID_USRA, "usra"},
	{InstructionIdentifier::ID_URSHR, "urshr"},
	{InstructionIdentifier::ID_URSRA, "ursra"},
	{InstructionIdentifier::ID_SRI, "sri"},
	{InstructionIdentifier::ID_SLI, "sli"},
	{InstructionIdentifier::ID_SQSHLU, "sqshlu"},
	{InstructionIdentifier::ID_SQSHRUN, "sqshrun"},
	{InstructionIdentifier::ID_SQRSHRUN, "sqrshrun"},
	{InstructionIdentifier::ID_UQSHRN, "uqshrn"},
	{InstructionIdentifier::ID_UQRSHRN, "uqrshrn"},
	{InstructionIdentifier::ID_SQRDMLAH, "sqrdmlah"},
	{InstructionIdentifier::ID_SQRDMLSH, "sqrdmlsh"},
	{InstructionIdentifier::ID_FMLA, "fmla"},
	{InstructionIdentifier::ID_FMLS, "fmls"},
	{InstructionIdentifier::ID_FMUL, "fmul"},
	{InstructionIdentifier::ID_TBL, "tbl"},
	{InstructionIdentifier::ID_TBLX, "tblx"},
	{InstructionIdentifier::ID_LUTI4, "luti4"},
	{InstructionIdentifier::ID_LUTI2, "luti2"},
	{InstructionIdentifier::ID_UZP1, "uzp1"},
	{InstructionIdentifier::ID_TRN1, "trn1"},
	{InstructionIdentifier::ID_ZIP1, "zip1"},
	{InstructionIdentifier::ID_UZP2, "uzp2"},
	{InstructionIdentifier::ID_TRN2, "trn2"},
	{InstructionIdentifier::ID_ZIP2, "zip2"},
	{InstructionIdentifier::ID_DUP, "dup"},
	{InstructionIdentifier::ID_SMOV, "smov"},
	{InstructionIdentifier::ID_UMOV, "umov"},
	{InstructionIdentifier::ID_INS, "ins"},
	{InstructionIdentifier::ID_FMAXNM, "fmaxnm"},
	{InstructionIdentifier::ID_FADD, "fadd"},
	{InstructionIdentifier::ID_FMAX, "fmax"},
	{InstructionIdentifier::ID_FMINNM, "fminnm"},
	{InstructionIdentifier::ID_FSUB, "fsub"},
	{InstructionIdentifier::ID_FAMAX, "famax"},
	{InstructionIdentifier::ID_FMIN, "fmin"},
	{InstructionIdentifier::ID_FDIV, "fdiv"},
	{InstructionIdentifier::ID_FAMIN, "famin"},
	{InstructionIdentifier::ID_FSCALE, "fscale"},
	{InstructionIdentifier::ID_FRINTN, "frintn"},
	{InstructionIdentifier::ID_FRINTM, "frintm"},
	{InstructionIdentifier::ID_FABS, "fabs"},
	{InstructionIdentifier::ID_FRINTP, "frintp"},
	{InstructionIdentifier::ID_FRINTZ, "frintz"},
	{InstructionIdentifier::ID_FRINTA, "frinta"},
	{InstructionIdentifier::ID_FRINTX, "frintx"},
	{InstructionIdentifier::ID_FNEG, "fneg"},
	{InstructionIdentifier::ID_FRINTI, "frinti"},
	{InstructionIdentifier::ID_FSQRT, "fsqrt"},
	{InstructionIdentifier::ID_SDOT, "sdot"},
	{InstructionIdentifier::ID_FCVTN, "fcvtn"},
	{InstructionIdentifier::ID_FCVTN2, "fcvtn2"},
	{InstructionIdentifier::ID_FDOT, "fdot"},
	{InstructionIdentifier::ID_USDOT, "usdot"},
	{InstructionIdentifier::ID_UDOT, "udot"},
	{InstructionIdentifier::ID_FCMLA, "fcmla"},
	{InstructionIdentifier::ID_FCADD, "fcadd"},
	{InstructionIdentifier::ID_BFDOT, "bfdot"},
	{InstructionIdentifier::ID_BFMLALB, "bfmlalb"},
	{InstructionIdentifier::ID_BFMLALT, "bfmlalt"},
	{InstructionIdentifier::ID_FMLALLBB, "fmlallbb"},
	{InstructionIdentifier::ID_FMLALLBT, "fmlallbt"},
	{InstructionIdentifier::ID_FMLALB, "fmlalb"},
	{InstructionIdentifier::ID_FMLALLTB, "fmlalltb"},
	{InstructionIdentifier::ID_FMLALLTT, "fmlalltt"},
	{InstructionIdentifier::ID_SMMLA, "smmla"},
	{InstructionIdentifier::ID_USMMLA, "usmmla"},
	{InstructionIdentifier::ID_FMLALT, "fmlalt"},
	{InstructionIdentifier::ID_FMMLA, "fmmla"},
	{InstructionIdentifier::ID_BFMMLA, "bfmmla"},
	{InstructionIdentifier::ID_UMMLA, "ummla"},
	{InstructionIdentifier::ID_REV64, "rev64"},
	{InstructionIdentifier::ID_SADDLP, "saddlp"},
	{InstructionIdentifier::ID_SADALP, "sadalp"},
	{InstructionIdentifier::ID_XTN2, "xtn2"},
	{InstructionIdentifier::ID_XTN, "xtn"},
	{InstructionIdentifier::ID_SQXTN2, "sqxtn2"},
	{InstructionIdentifier::ID_UADDLP, "uaddlp"},
	{InstructionIdentifier::ID_UADALP, "uadalp"},
	{InstructionIdentifier::ID_SQXTUN2, "sqxtun2"},
	{InstructionIdentifier::ID_SHLL2, "shll2"},
	{InstructionIdentifier::ID_SHLL, "shll"},
	{InstructionIdentifier::ID_UQXTN2, "uqxtn2"},
	{InstructionIdentifier::ID_FCVTL2, "fcvtl2"},
	{InstructionIdentifier::ID_FCVTL, "fcvtl"},
	{InstructionIdentifier::ID_FRINT32Z, "frint32z"},
	{InstructionIdentifier::ID_FRINT64Z, "frint64z"},
	{InstructionIdentifier::ID_URECPE, "urecpe"},
	{InstructionIdentifier::ID_BFCVTN2, "bfcvtn2"},
	{InstructionIdentifier::ID_BFCVTN, "bfcvtn"},
	{InstructionIdentifier::ID_FRINT32X, "frint32x"},
	{InstructionIdentifier::ID_FRINT64X, "frint64x"},
	{InstructionIdentifier::ID_NOT, "not"},
	{InstructionIdentifier::ID_F1CVTL2, "f1cvtl2"},
	{InstructionIdentifier::ID_F1CVTL, "f1cvtl"},
	{InstructionIdentifier::ID_FCVTXN2, "fcvtxn2"},
	{InstructionIdentifier::ID_F2CVTL2, "f2cvtl2"},
	{InstructionIdentifier::ID_F2CVTL, "f2cvtl"},
	{InstructionIdentifier::ID_URSQRTE, "ursqrte"},
	{InstructionIdentifier::ID_BF1CVTL2, "bf1cvtl2"},
	{InstructionIdentifier::ID_BF1CVTL, "bf1cvtl"},
	{InstructionIdentifier::ID_BF2CVTL2, "bf2cvtl2"},
	{InstructionIdentifier::ID_BF2CVTL, "bf2cvtl"},
	{InstructionIdentifier::ID_SADDLV, "saddlv"},
	{InstructionIdentifier::ID_SMAXV, "smaxv"},
	{InstructionIdentifier::ID_SMINV, "sminv"},
	{InstructionIdentifier::ID_ADDV, "addv"},
	{InstructionIdentifier::ID_FMAXNMV, "fmaxnmv"},
	{InstructionIdentifier::ID_FMAXV, "fmaxv"},
	{InstructionIdentifier::ID_FMINNV, "fminnv"},
	{InstructionIdentifier::ID_FMINV, "fminv"},
	{InstructionIdentifier::ID_UADDLV, "uaddlv"},
	{InstructionIdentifier::ID_UMAXV, "umaxv"},
	{InstructionIdentifier::ID_UMINV, "uminv"},
	{InstructionIdentifier::ID_FMINNMV, "fminnmv"},
	{InstructionIdentifier::ID_SADDL, "saddl"},
	{InstructionIdentifier::ID_SAADW, "saadw"},
	{InstructionIdentifier::ID_SSUBL, "ssubl"},
	{InstructionIdentifier::ID_SSUBW, "ssubw"},
	{InstructionIdentifier::ID_ADDHN, "addhn"},
	{InstructionIdentifier::ID_SABAL, "sabal"},
	{InstructionIdentifier::ID_SUBHN, "subhn"},
	{InstructionIdentifier::ID_SABDL, "sabdl"},
	{InstructionIdentifier::ID_SMLAL, "smlal"},
	{InstructionIdentifier::ID_SMLSL, "smlsl"},
	{InstructionIdentifier::ID_PMULL, "pmull"},
	{InstructionIdentifier::ID_UADDL, "uaddl"},
	{InstructionIdentifier::ID_UAADW, "uaadw"},
	{InstructionIdentifier::ID_USUBL, "usubl"},
	{InstructionIdentifier::ID_USUBW, "usubw"},
	{InstructionIdentifier::ID_RADDHN, "raddhn"},
	{InstructionIdentifier::ID_UABAL, "uabal"},
	{InstructionIdentifier::ID_RSUBHN, "rsubhn"},
	{InstructionIdentifier::ID_UABDL, "uabdl"},
	{InstructionIdentifier::ID_UMLAL, "umlal"},
	{InstructionIdentifier::ID_UMLSL, "umlsl"},
	{InstructionIdentifier::ID_SHADD, "shadd"},
	{InstructionIdentifier::ID_SRHADD, "srhadd"},
	{InstructionIdentifier::ID_SHSUB, "shsub"},
	{InstructionIdentifier::ID_SABD, "sabd"},
	{InstructionIdentifier::ID_SABA, "saba"},
	{InstructionIdentifier::ID_MLA, "mla"},
	{InstructionIdentifier::ID_SMAXP, "smaxp"},
	{InstructionIdentifier::ID_SMINP, "sminp"},
	{InstructionIdentifier::ID_UHADD, "uhadd"},
	{InstructionIdentifier::ID_URHADD, "urhadd"},
	{InstructionIdentifier::ID_UHSUB, "uhsub"},
	{InstructionIdentifier::ID_UABD, "uabd"},
	{InstructionIdentifier::ID_UABA, "uaba"},
	{InstructionIdentifier::ID_MLS, "mls"},
	{InstructionIdentifier::ID_PMUL, "pmul"},
	{InstructionIdentifier::ID_UMAXP, "umaxp"},
	{InstructionIdentifier::ID_UMINP, "uminp"},
	{InstructionIdentifier::ID_FMLAL, "fmlal"},
	{InstructionIdentifier::ID_FMLSL, "fmlsl"},
	{InstructionIdentifier::ID_FMLAL2, "fmlal2"},
	{InstructionIdentifier::ID_BSL, "bsl"},
	{InstructionIdentifier::ID_BIT, "bit"},
	{InstructionIdentifier::ID_FMLSL2, "fmlsl2"},
	{InstructionIdentifier::ID_BIF, "bif"},
	{InstructionIdentifier::ID_MOVI, "movi"},
	{InstructionIdentifier::ID_FMOV, "fmov"},
	{InstructionIdentifier::ID_MVNI, "mvni"},
	{InstructionIdentifier::ID_SHRN2, "shrn2"},
	{InstructionIdentifier::ID_SHRN, "shrn"},
	{InstructionIdentifier::ID_RSHRN2, "rshrn2"},
	{InstructionIdentifier::ID_RSHRN, "rshrn"},
	{InstructionIdentifier::ID_SQSHRN2, "sqshrn2"},
	{InstructionIdentifier::ID_SQRSHRN2, "sqrshrn2"},
	{InstructionIdentifier::ID_SSHLL2, "sshll2"},
	{InstructionIdentifier::ID_SSHLL, "sshll"},
	{InstructionIdentifier::ID_SQSHRUN2, "sqshrun2"},
	{InstructionIdentifier::ID_SQRSHRUN2, "sqrshrun2"},
	{InstructionIdentifier::ID_UQSHRN2, "uqshrn2"},
	{InstructionIdentifier::ID_UQRSHRN2, "uqrshrn2"},
	{InstructionIdentifier::ID_USHLL2, "ushll2"},
	{InstructionIdentifier::ID_USHLL, "ushll"},
	{InstructionIdentifier::ID_SMLAL2, "smlal2"},
	{InstructionIdentifier::ID_SQDMLAL2, "sqdmlal2"},
	{InstructionIdentifier::ID_SMLSL2, "smlsl2"},
	{InstructionIdentifier::ID_SQDMLSL2, "sqdmlsl2"},
	{InstructionIdentifier::ID_SMULL2, "smull2"},
	{InstructionIdentifier::ID_SQDMULL2, "sqdmull2"},
	{InstructionIdentifier::ID_SQDRMULH, "sqdrmulh"},
	{InstructionIdentifier::ID_UMLAL2, "umlal2"},
	{InstructionIdentifier::ID_UMLSL2, "umlsl2"},
	{InstructionIdentifier::ID_UMULL2, "umull2"},
	{InstructionIdentifier::ID_SUDOT, "sudot"},
	{InstructionIdentifier::ID_SM3TT1A, "sm3tt1a"},
	{InstructionIdentifier::ID_SM3TT1B, "sm3tt1b"},
	{InstructionIdentifier::ID_SM3TT2A, "sm3tt2a"},
	{InstructionIdentifier::ID_SM3TT2B, "sm3tt2b"},
	{InstructionIdentifier::ID_SHA512H, "sha512h"},
	{InstructionIdentifier::ID_SHA512H2, "sha512h2"},
	{InstructionIdentifier::ID_SHA512SU1, "sha512su1"},
	{InstructionIdentifier::ID_RAX1, "rax1"},
	{InstructionIdentifier::ID_SM3PARTW1, "sm3partw1"},
	{InstructionIdentifier::ID_SM3PARTW2, "sm3partw2"},
	{InstructionIdentifier::ID_SM4EKEY, "sm4ekey"},
	{InstructionIdentifier::ID_EOR3, "eor3"},
	{InstructionIdentifier::ID_BCAX, "bcax"},
	{InstructionIdentifier::ID_SM3SS1, "sm3ss1"},
	{InstructionIdentifier::ID_SHA512SU0, "sha512su0"},
	{InstructionIdentifier::ID_SM4E, "sm4e"},
	{InstructionIdentifier::ID_UCVTZS, "ucvtzs"},
	{InstructionIdentifier::ID_FJCVTZS, "fjcvtzs"},
	{InstructionIdentifier::ID_FCVT, "fcvt"},
	{InstructionIdentifier::ID_BFCVT, "bfcvt"},
	{InstructionIdentifier::ID_FCMP, "fcmp"},
	{InstructionIdentifier::ID_FCMPE, "fcmpe"},
	{InstructionIdentifier::ID_FCCMP, "fccmp"},
	{InstructionIdentifier::ID_FCCMPE, "fccmpe"},
	{InstructionIdentifier::ID_FNMUL, "fnmul"},
	{InstructionIdentifier::ID_FCSEL, "fcsel"},
	{InstructionIdentifier::ID_FMADD, "fmadd"},
	{InstructionIdentifier::ID_FMSUB, "fmsub"},
	{InstructionIdentifier::ID_FNMADD, "fnmadd"},
	{InstructionIdentifier::ID_FNMSUB, "fnmsub"},
	{InstructionIdentifier::ID_SADDL2, "saddl2"},
	{InstructionIdentifier::ID_SAADW2, "saadw2"},
	{InstructionIdentifier::ID_SSUBL2, "ssubl2"},
	{InstructionIdentifier::ID_SSUBW2, "ssubw2"},
	{InstructionIdentifier::ID_ADDHN2, "addhn2"},
	{InstructionIdentifier::ID_SABAL2, "sabal2"},
	{InstructionIdentifier::ID_SUBHN2, "subhn2"},
	{InstructionIdentifier::ID_SABDL2, "sabdl2"},
	{InstructionIdentifier::ID_PMULL2, "pmull2"},
	{InstructionIdentifier::ID_UADDL2, "uaddl2"},
	{InstructionIdentifier::ID_UAADW2, "uaadw2"},
	{InstructionIdentifier::ID_USUBL2, "usubl2"},
	{InstructionIdentifier::ID_USUBW2, "usubw2"},
	{InstructionIdentifier::ID_RADDHN2, "raddhn2"},
	{InstructionIdentifier::ID_UABAL2, "uabal2"},
	{InstructionIdentifier::ID_RSUBHN2, "rsubhn2"},
	{InstructionIdentifier::ID_UABDL2, "uabdl2"},
	{InstructionIdentifier::ID_SXTL, "sxtl"},
	{InstructionIdentifier::ID_SXTL2, "sxtl2"},
	{InstructionIdentifier::ID_UXTL, "uxtl"},
	{InstructionIdentifier::ID_UXTL2, "uxtl2"},
	{InstructionIdentifier::ID_XAR, "xar"},
	{InstructionIdentifier::ID_ST1, "st1"},
	{InstructionIdentifier::ID_ST2, "st2"},
	{InstructionIdentifier::ID_ST3, "st3"},
	{InstructionIdentifier::ID_ST4, "st4"},
	{InstructionIdentifier::ID_LD1, "ld1"},
	{InstructionIdentifier::ID_LD2, "ld2"},
	{InstructionIdentifier::ID_LD3, "ld3"},
	{InstructionIdentifier::ID_LD4, "ld4"},
	{InstructionIdentifier::ID_GCSSTR, "gcsstr"},
	{InstructionIdentifier::ID_GCSSTTR, "gcssttr"},
	{InstructionIdentifier::ID_RCWCASP, "rcwcasp"},
	{InstructionIdentifier::ID_RCWCASPL, "rcwcaspl"},
	{InstructionIdentifier::ID_RCWCASPA, "rcwcaspa"},
	{InstructionIdentifier::ID_RCWCASPAL, "rcwcaspal"},
	{InstructionIdentifier::ID_RCWSCASP, "rcwscasp"},
	{InstructionIdentifier::ID_RCWSCASPL, "rcwscaspl"},
	{InstructionIdentifier::ID_RCWSCASPA, "rcwscaspa"},
	{InstructionIdentifier::ID_RCWSCASPAL, "rcwscaspal"},
	{InstructionIdentifier::ID_RCWCAS, "rcwcas"},
	{InstructionIdentifier::ID_RCWCASL, "rcwcasl"},
	{InstructionIdentifier::ID_RCWCASA, "rcwcasa"},
	{InstructionIdentifier::ID_RCWCASAL, "rcwcasal"},
	{InstructionIdentifier::ID_RCWSCAS, "rcwscas"},
	{InstructionIdentifier::ID_RCWSCASL, "rcwscasl"},
	{InstructionIdentifier::ID_RCWSCASA, "rcwscasa"},
	{InstructionIdentifier::ID_RCWSCASAL, "rcwscasal"},
	{InstructionIdentifier::ID_STG, "stg"},
	{InstructionIdentifier::ID_STZG, "stzg"},
	{InstructionIdentifier::ID_ST2G, "st2g"},
	{InstructionIdentifier::ID_STZ2G, "stz2g"},
	{InstructionIdentifier::ID_STZGM, "stzgm"},
	{InstructionIdentifier::ID_LDG, "ldg"},
	{InstructionIdentifier::ID_STGM, "stgm"},
	{InstructionIdentifier::ID_LDGM, "ldgm"},
	{InstructionIdentifier::ID_STXP, "stxp"},
	{InstructionIdentifier::ID_STLXP, "stlxp"},
	{InstructionIdentifier::ID_LDXP, "ldxp"},
	{InstructionIdentifier::ID_LDAXP, "ldaxp"},
	{InstructionIdentifier::ID_STXR, "stxr"},
	{InstructionIdentifier::ID_STLXR, "stlxr"},
	{InstructionIdentifier::ID_LDXR, "ldxr"},
	{InstructionIdentifier::ID_LDAXR, "ldaxr"},
	{InstructionIdentifier::ID_STXRB, "stxrb"},
	{InstructionIdentifier::ID_STLXRB, "stlxrb"},
	{InstructionIdentifier::ID_LDXRB, "ldxrb"},
	{InstructionIdentifier::ID_LDAXRB, "ldaxrb"},
	{InstructionIdentifier::ID_STXRH, "stxrh"},
	{InstructionIdentifier::ID_STLXRH, "stlxrh"},
	{InstructionIdentifier::ID_LDXRH, "ldxrh"},
	{InstructionIdentifier::ID_LDAXRH, "ldaxrh"},
	{InstructionIdentifier::ID_STLLRB, "stllrb"},
	{InstructionIdentifier::ID_STLRB, "stlrb"},
	{InstructionIdentifier::ID_LDLARB, "ldlarb"},
	{InstructionIdentifier::ID_LDARB, "ldarb"},
	{InstructionIdentifier::ID_STLLRH, "stllrh"},
	{InstructionIdentifier::ID_STLRH, "stlrh"},
	{InstructionIdentifier::ID_LDLARH, "ldlarh"},
	{InstructionIdentifier::ID_LDARH, "ldarh"},
	{InstructionIdentifier::ID_STLLR, "stllr"},
	{InstructionIdentifier::ID_STLR, "stlr"},
	{InstructionIdentifier::ID_LDLAR, "ldlar"},
	{InstructionIdentifier::ID_LDAR, "ldar"},
	{InstructionIdentifier::ID_CASB, "casb"},
	{InstructionIdentifier::ID_CASLB, "caslb"},
	{InstructionIdentifier::ID_CASAB, "casab"},
	{InstructionIdentifier::ID_CASALB, "casalb"},
	{InstructionIdentifier::ID_CASH, "cash"},
	{InstructionIdentifier::ID_CASLH, "caslh"},
	{InstructionIdentifier::ID_CASAH, "casah"},
	{InstructionIdentifier::ID_CASALH, "casalh"},
	{InstructionIdentifier::ID_CAS, "cas"},
	{InstructionIdentifier::ID_CASL, "casl"},
	{InstructionIdentifier::ID_CASA, "casa"},
	{InstructionIdentifier::ID_CASAL, "casal"},
	{InstructionIdentifier::ID_STILP, "stilp"},
	{InstructionIdentifier::ID_LDIAPP, "ldiapp"},
	{InstructionIdentifier::ID_PRFM, "prfm"},
	{InstructionIdentifier::ID_PRFUM, "prfum"},
	{InstructionIdentifier::ID_LDRAB, "ldrab"},
	{InstructionIdentifier::ID_LDRAA, "ldraa"},
	{InstructionIdentifier::ID_B, "b"},
	{InstructionIdentifier::ID_BC, "bc"},
	{InstructionIdentifier::ID_WFET, "wfet"},
	{InstructionIdentifier::ID_WFIT, "wfit"},
	{InstructionIdentifier::ID_HINT, "hint"},
	{InstructionIdentifier::ID_SMSTART, "smstart"},
	{InstructionIdentifier::ID_SMSTOP, "smstop"},
	{InstructionIdentifier::ID_MSR, "msr"},
	{InstructionIdentifier::ID_AT, "at"},
	{InstructionIdentifier::ID_SYSL, "sysl"},
	{InstructionIdentifier::ID_BRB, "brb"},
	{InstructionIdentifier::ID_DC, "dc"},
	{InstructionIdentifier::ID_IC, "ic"},
	{InstructionIdentifier::ID_TLBI, "tlbi"},
	{InstructionIdentifier::ID_MRS, "mrs"},
	{InstructionIdentifier::ID_TLBIP, "tlbip"},
	{InstructionIdentifier::ID_MRRS, "mrrs"},
	{InstructionIdentifier::ID_MSRR, "msrr"},
	{InstructionIdentifier::ID_BL, "bl"},
	{InstructionIdentifier::ID_CBZ, "cbz"},
	{InstructionIdentifier::ID_CBNZ, "cbnz"},
	{InstructionIdentifier::ID_NEGS, "negs"},
	{InstructionIdentifier::ID_RMIF, "rmif"},
	{InstructionIdentifier::ID_CINC, "cinc"},
	{InstructionIdentifier::ID_CSET, "cset"},
	{InstructionIdentifier::ID_CINV, "cinv"},
	{InstructionIdentifier::ID_CSETM, "csetm"},
	{InstructionIdentifier::ID_CNEG, "cneg"},
	{InstructionIdentifier::ID_ADR, "adr"},
	{InstructionIdentifier::ID_ADRP, "adrp"},
	{InstructionIdentifier::ID_ASR, "asr"},
	{InstructionIdentifier::ID_SBFIZ, "sbfiz"},
	{InstructionIdentifier::ID_SBFX, "sbfx"},
	{InstructionIdentifier::ID_BFC, "bfc"},
	{InstructionIdentifier::ID_BFI, "bfi"},
	{InstructionIdentifier::ID_BFXIL, "bfxil"},
	{InstructionIdentifier::ID_LSL, "lsl"},
	{InstructionIdentifier::ID_LSR, "lsr"},
	{InstructionIdentifier::ID_UBFIZ, "ubfiz"},
	{InstructionIdentifier::ID_UBFX, "ubfx"},
	{InstructionIdentifier::ID_ROR, "ror"}
};

auto std::formatter<disxx::disasm::Instruction>::format(const disxx::disasm::Instruction &insn, std::format_context &ctx) const
{
	using namespace disxx::disasm;

	const auto &id{insn.GetInstructionIdentifier()};
	const auto &oprs{insn.GetOperands()};

	std::stringstream str;
	str << s_MnemonicTable.at(id).data();
	
	switch (id)
	{
	  case InstructionIdentifier::ID_TBL: [[fallthrough]];
	  case InstructionIdentifier::ID_TBLX: [[fallthrough]];
	  case InstructionIdentifier::ID_LUTI2: [[fallthrough]];
	  case InstructionIdentifier::ID_LUTI4:
	  {
		for (auto i{0UL}; const auto &ptr : oprs)
		{
			if (i == 1)
				str << " {";
			else if (i == oprs.size() - 1)
				str << " }";
			str
				<< (i == 0 ? " " : ", ")
				<< ptr->GetMnemonic();
			i++;
		}

		return std::format_to
		(
			ctx.out(),
			"{}",
			str.str()
		);
	  }

	  case InstructionIdentifier::ID_ST1: [[fallthrough]];
	  case InstructionIdentifier::ID_ST2: [[fallthrough]];
	  case InstructionIdentifier::ID_ST3: [[fallthrough]];
	  case InstructionIdentifier::ID_ST4: [[fallthrough]];
	  case InstructionIdentifier::ID_LD1: [[fallthrough]];
	  case InstructionIdentifier::ID_LD2: [[fallthrough]];
	  case InstructionIdentifier::ID_LD3: [[fallthrough]];
	  case InstructionIdentifier::ID_LD4: [[fallthrough]];
	  case InstructionIdentifier::ID_STL1: [[fallthrough]];
	  case InstructionIdentifier::ID_LD1R: [[fallthrough]];
	  case InstructionIdentifier::ID_LD2R: [[fallthrough]];
	  case InstructionIdentifier::ID_LD3R: [[fallthrough]];
	  case InstructionIdentifier::ID_LD4R: [[fallthrough]];
	  case InstructionIdentifier::ID_LDAP1:
	  {
		// FIXME: Should be able to handle all kinds of these instructions
		str << " {";
	  	for (auto i{0UL}; const auto &ptr : oprs)
		{
			if (i == oprs.size() - 2)
				str << " }";
			str
				<< (i == 0 ? " " : ", ")
				<< ptr->GetMnemonic();
			i++;
		}

		return std::format_to
		(
			ctx.out(),
			"{}",
			str.str()
		);
	  }

	  case InstructionIdentifier::ID_SYSL:
	  {
		if (oprs.size() != 5) [[unlikely]]
			throw std::logic_error{"OperandsCountError"};

		if ((*oprs.begin())->GetType() == operand::AbstractOperand::Type::TYPE_REGISTER)
		{
			for (auto i{0UL}; const auto &ptr : oprs)
			{
				if (i == 1 || i == oprs.size() - 1)
					str
						<< ", "
						<< std::regex_replace
						(
							ptr->GetMnemonic(),
							std::regex{R"(#0x)"},
							"c"
						);
				else
					str
						<< (i == 0 ? " " : ", ")
						<< ptr->GetMnemonic();
				i++;
			}
		
			return std::format_to
			(
				ctx.out(),
				"{}",
				str.str()
			);
		}

		for (auto i{0UL}; const auto &ptr : oprs)
		{
			if (i == 0 || i == 3)
				str
					<< ", "
					<< std::regex_replace
					(
						ptr->GetMnemonic(),
						std::regex{R"(#0x)"},
						"c"
					);
			else
				str
					<< (i == 0 ? " " : ", ")
					<< ptr->GetMnemonic();
			i++;
		}

		return std::format_to
		(
			ctx.out(),
			"{}",
			str.str()
		);
	  }

	  default:
	  {
		for (auto i{0UL}; const auto &ptr : oprs)
		{
	  		str
				<< (
					i == 0 && ptr->GetType() == operand::AbstractOperand::Type::TYPE_CONDITION
						? "."
						: (
							i == 0 || (i == 1 && oprs.at(0)->GetType() == operand::AbstractOperand::Type::TYPE_CONDITION)
								? " "
								: ", "
						)
				)
				<< ptr->GetMnemonic();
			i++;
		}

		return std::format_to
		(
			ctx.out(),
			"{}",
			str.str()
		);
	  }
	}
}
*/
